### ISSUE TITLE
Option to grab the Wikidata lexemes for queried words

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Data#101]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

ALL

### Description

This issue is for the implementation of one of the ideas brought up in #59, in particular:

> - For nouns, verbs, and prepositions, this is likely the Wikidata lexemes.

**Comment by andrewtavis** [comment]
For someone with interest in working on this, this should be as simple as adding `?lexeme` as the first element in the select statement for all `.sparql` files :)

**Comment by wkyoshida** [comment]
Hey @oreotamish 👋 
@mhmohona actually DM'ed earlier today expressing interest in this issue as well.. sorry about this, but is there another issue that you might interested in picking up?

**Comment by oreotamish** [comment]
Sure

**Comment by wkyoshida** [comment]
Thank you for understanding, @oreotamish! :pray::grin: 
I did later realize though that I did simply assume that your interest was due to our participation in GSoC. Apologies if that was an incorrect assumption! :pleading_face: 
If however GSoC is indeed how you found us, I do also realize that we're running low on available issues as well, given the amount of traffic that we're getting. I'll try to create some more issues soon. If you're interested, feel free to take a look at [`good first issues`](https://github.com/orgs/scribe-org/projects/1/views/9) we have throughout the organization.

@mhmohona add a comment here when you can as well please, as we can only assign once someone's active in the issue

**Comment by mhmohona** [comment]
I would like to work on this issue.

**Comment by andrewtavis** [comment]
@mhmohona, just a quick note here that came from a discussion with @henrikth93: the way we'd like to get the lexeme IDs for this would be the following:

```sql
SELECT 
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") as ?lexemeID)
  OTHER_COLUMS_LIKE_NOUN_OR_VERB_ETC
```

The `?lexemeID` line gets us just the LID, not `wd:LID` as comes from just returning `?lexeme` :)
