### ISSUE TITLE
Implement Japanese noun queries

### ISSUE THREAD

**Issue by henrikth93** [scribe-org/Scribe-Data#105]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Japanese

### Description

Implement Japanese noun queries using SPARQL

**Comment by andrewtavis** [comment]
Closed by #119 🥳 Thanks, @henrikth93! 🙌
