### ISSUE TITLE
Implement Japanese verb queries

### ISSUE THREAD

**Issue by henrikth93** [scribe-org/Scribe-Data#106]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Japanese

### Description

Implement Japanese verb queries using SPARQL.

**Comment by andrewtavis** [comment]
Do you have an idea on how this could be improved, @wkyoshida? Maybe we can check some of the statements that are on a Japanese query and decide which verb conjugations we want to include at the start?

**Comment by AnishereMariam** [comment]
Hi, @andrewtavis, I noticed the Japanese verb query displays an empty result. I fixed the error and added it to a commit. I tried adding the verb conjugates as well, but it's not coming up like I wanted. I called the Option Function but it keeps returning the column as empty. I had the same issue while updating the Yoruba query as well. Any support would be greatly appreciated. Thank you. Kindly find the image below for reference:

![image](https://github.com/user-attachments/assets/31582868-4467-48cd-b449-fef7a48279b2)

**Comment by henrikth93** [comment]
> Hi, @andrewtavis, I noticed the Japanese verb query displays an empty result. I fixed the error and added it to a commit. I tried adding the verb conjugates as well, but it's not coming up like I wanted. I called the Option Function but it keeps returning the column as empty. I had the same issue while updating the Yoruba query as well. Any support would be greatly appreciated. Thank you. Kindly find the image below for reference:
> 
> ![image](https://private-user-images.githubusercontent.com/37239247/373212330-31582868-4467-48cd-b449-fef7a48279b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5Njk4OTUsIm5iZiI6MTcyNzk2OTU5NSwicGF0aCI6Ii8zNzIzOTI0Ny8zNzMyMTIzMzAtMzE1ODI4NjgtNDQ2Ny00OGNkLWI0NDktZmVmN2E0ODI3OWIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDAzVDE1MzMxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4N2MwNDFkNmMzZGI1OWZkM2U4ZmNjOGY1NDdkMjkyNjcyNjliNGYzZjY2NmQ5NmY0MzRkNjE5MWVmNzU3NzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NNuqVt0ejoaDxPsUx_32Ns_XpgcKM4cz0tad5iEtMYE)

Hello AnishereMariam! I was the one that wrote that query (probably in collaboration with Andrew!) Do you want to take a look at it? Are you in the Matrix chat, if so, write to me there.
Best Regards
