### ISSUE TITLE
[deleted] Set up update_data.py to also edit readme files

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#11]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

An interesting feature to add to [scribe_data/load/update_data.py](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/load/update_data.py) would be to have it edit the readme files for each of the repositories. The information from [_update_files/data_table.txt](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/_update_files/data_table.txt) should be added to each readme after this is complete, with this currently being done by hand. This could be achieved by splitting the readme file into different subfiles that would then be combined as described in [the answer to this SO question](https://stackoverflow.com/a/21780837). 

Readme edits in the future will predominantly be to update this table, and the table appears in more than one repo, so the benefits of this automation are significant. The goal would be that the readme files for each would be updated by [scribe_data/load/update_data.py](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/load/update_data.py), and then separate commits could be made directly.

### Contribution

This isn't a priority as of now, but will eventually need to be done. I'd be happy to collaborate on this whenever if someone has interest though :)

**Comment by Rishav-12** [comment]
The link to data_table.txt is broken. It should be https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/_update_files/data_table.txt. The folder structure changed maybe?

**Comment by andrewtavis** [comment]
Thank you for pointing this out, @Rishav-12! I switched the structure a few months ago when I converted it into a package. I think it'd be easier for us to eventually import it into the iOS and other apps if it can be installed easily.

Very much appreciate you taking the time :)

**Comment by andrewtavis** [comment]
Closing this issue as I really don't think that there's a significant benefit at this point.
