### ISSUE TITLE
Edit and expand Arabic data processes

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#115]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would check and expand the queries and related data processes found in the [scribe_data/extract_transform/languages/Arabic](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/extract_transform/languages/Arabic) directory. It would be great to start with expanding the queries found in the nouns and verbs directory, and then from there we can discuss a formatting process :) The [query_nouns.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/Arabic/nouns/query_nouns.sparql) and [query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/Arabic/nouns/query_nouns.sparql) files can be expanded on using the similar queries found for other languages. The formatting process should wait until the formatting process is expanded to focus on individual lexemes.

### Contribution

Happy to support someone who has interest in working on this! 😊

**Comment by andrewtavis** [comment]
CC @mrbazzan who had interest in this! Please write in the issue and I'll assign! Also let me know if there are any questions :)

**Comment by mrbazzan** [comment]
I would like to start with this one.

**Comment by andrewtavis** [comment]
Fantastic, @mrbazzan! Let me know if there's anything we can do to help :)

**Comment by mrbazzan** [comment]
All I can think of right now is to copy some of the optional queries
from [German's query_nouns.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/German/nouns/query_nouns.sparql) to Arabic's own but I don't
really understand what that does or what's going on.

Is there anything else to be considered?

**Comment by andrewtavis** [comment]
Look into some of the Arabic lexemes and see if there are other properties or statements that could be added. There might not be though, so feel free to send along the basic files converted from German to Arabic!

**Comment by mrbazzan** [comment]
> Look into some of the Arabic lexemes and see if there are other properties or statements that could be added. 

What do you mean? I tried a couple of queries and they contain a lot of duplicate data.

**Comment by andrewtavis** [comment]
Duplicate how, @mrbazzan? So take the query below for Arabic verbs:

```sql
# All Arabic (Q13955) verbs.
# Enter this query at https://query.wikidata.org/.

SELECT
  ?lexeme
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") as ?lexemeID)
  ?verb

WHERE {
  ?lexeme a ontolex:LexicalEntry ;
    dct:language wd:Q13955 ;
    wikibase:lexicalCategory wd:Q24905 ;
    wikibase:lemma ?verb .
}
```

From there you can check out a Lexeme like [this one](https://www.wikidata.org/wiki/Lexeme:L12100) that also has statements for verb conjugations. Could you expand the query by referencing other verbs queries for other languages to then also get the conjugations for the verbs?

**Comment by mrbazzan** [comment]
Hello, @andrewtavis
Sorry for the late reply (Holidays).
I'll submit a draft PR just to show what I've been doing

**Comment by andrewtavis** [comment]
Closing this as the current state of the Arabic queries are in quite good share after #127 and other changes. Thanks for this, @mrbazzan!
