### ISSUE TITLE
Edit and expand Hausa data processes

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#116]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would check and expand the queries and related data processes found in the [scribe_data/extract_transform/languages/Hausa](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/extract_transform/languages/Hausa) directory. It would be great to start with expanding the queries found in the nouns and verbs directory, and then from there we can discuss a formatting process :) The [query_nouns.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/Hausa/nouns/query_nouns.sparql) and [query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/Hausa/nouns/query_verbs.sparql) files can be expanded on using the similar queries found for other languages. The formatting process should wait until the formatting process is expanded to focus on individual lexemes.

### Contribution

Happy to support someone who has interest in working on this! 😊

**Comment by siva224513** [comment]
I would like to work on this issue @andrewtavis

**Comment by andrewtavis** [comment]
@siva224513, let me know if you need any support here? :)

**Comment by Collins-Webdev** [comment]
Hello @andrewtavis 👋🏼,
How are you doing ?
I just made a PR about this issue here : https://github.com/scribe-org/Scribe-Data/pull/461
Please review it and let me know if I should modify something 😊.

**Comment by andrewtavis** [comment]
Closed by 7f5586a :) Thanks all for the work here!
