### ISSUE TITLE
Add a query for Japanese adjectives.

### ISSUE THREAD

**Issue by henrikth93** [scribe-org/Scribe-Data#120]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Japanese

### Description

Add a query for Japanese adjectives.

**Comment by andrewtavis** [comment]
Closed by #121 🚀 Thanks for handling all these, @henrikth93!
