### ISSUE TITLE
Expand Scribe-Data paths to allow for Windows commands

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#125]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that would be great to add to Scribe-Data is some more documentation for Windows commands beneath their Linux/Mac counterparts in the readme and contributing guide as well as converting some of the path functionality of the codebase over to allow for Windows paths to be accessed.

- Note that this should be worked on after #122 :)

### Contribution

Happy to support on this as needed! 😊

**Comment by mhmohona** [comment]
Yes.

**Comment by andrewtavis** [comment]
Assigned, @mhmohona! Let me know if there's anything we can do to assist :)

**Comment by Jk40git** [comment]
> Assigned, @mhmohona! Let me know if there's anything we can do to assist :)

Could assist too if you don't mind

**Comment by andrewtavis** [comment]
Sure thing, @Jk40git. @mhmohona, let either of us know it anything's needed :)

**Comment by mhmohona** [comment]
So the first problem I faced while installing Scribe-data was installing PyICU. It has different installation process for Windows - https://github.com/ilius/pyglossary/blob/master/doc/pyicu.md#installation-on-windows

**Comment by Jk40git** [comment]
> So the first problem I faced while installing Scribe-data was installing PyICU. It has different installation process for Windows - https://github.com/ilius/pyglossary/blob/master/doc/pyicu.md#installation-on-windows

@mhmohona have you tried the process? I can't load PyICU-2.9-cp311-cp311-win_amd64.whl into the command prompt

**Comment by Jk40git** [comment]
> > So the first problem I faced while installing Scribe-data was installing PyICU. It has different installation process for Windows - https://github.com/ilius/pyglossary/blob/master/doc/pyicu.md#installation-on-windows
> 
> @mhmohona have you tried the process? I can't load PyICU-2.9-cp311-cp311-win_amd64.whl into the command prompt


![Screenshot 2024-03-27 195043](https://github.com/scribe-org/Scribe-Data/assets/125589910/a427ba66-bfe8-4f64-b231-2260888aa642)

**Comment by Jk40git** [comment]
> > So the first problem I faced while installing Scribe-data was installing PyICU. It has different installation process for Windows - https://github.com/ilius/pyglossary/blob/master/doc/pyicu.md#installation-on-windows
> 
> @mhmohona have you tried the process? I can't load PyICU-2.9-cp311-cp311-win_amd64.whl into the command prompt

We need to install a certain pkg-config file using chocolatey

**Comment by andrewtavis** [comment]
Big thing to note here is that the PyICU behavior is known to be very weird... This is documented in #33, and I'd say that the install for PyICU for windows could be included in that issue. For this one, let's focus on the baseline paths for updating the data :) 

CC @wkyoshida

**Comment by Jk40git** [comment]
@mhmohona please where are you with this issue

**Comment by mhmohona** [comment]
Hey @Jk40git, I actually havent started working on this issue after my last comment.
However, I can suggest you an alternative to run the scripts without needing to installing locally. You can use Google Colab. Here I have setup the repo and other things - [link](https://colab.research.google.com/drive/1uxkTL84UpZomRcmLWLmjNdu8--zuD1-y?usp=sharing). You can use this notebook as reference.
Also, remember to reduce `batch_size` to `10`, otherwise you will get error.

**Comment by mhmohona** [comment]
Hey [@Jk40git](https://github.com/Jk40git), I actually havent started working on this issue after my last comment.
However, I can suggest you an alternative to run the scripts without needing to installing locally. You can use Google Colab. Here I have setup the repo and other things - [link](https://colab.research.google.com/drive/1uxkTL84UpZomRcmLWLmjNdu8--zuD1-y?usp=sharing). You can use this notebook as reference.

**Comment by Jk40git** [comment]
All right @mhmohona. I was able to access the path locally though. But my problem was the marisa-trie build wheels. Thanks for the reply

**Comment by andrewtavis** [comment]
This'll be solved over the weekend odds are :) We're discussing how to change the dependencies in #61, with the likely change being that we'll remove the ones that are causing all these issues.

**Comment by mhmohona** [comment]
Now in windows I can install Scribe data by following commands [here](https://github.com/scribe-org/Scribe-Data?tab=readme-ov-file#environment-setup) but when trying to run a script, getting error like this - 
![image](https://github.com/scribe-org/Scribe-Data/assets/14244685/5ba0d60e-2c89-4300-a6cb-f53f80a35b59)

This issue seems it will take some time. Thus I want to work on it later.

**Comment by Jk40git** [comment]
> Now in windows I can install Scribe data by following commands [here](https://github.com/scribe-org/Scribe-Data?tab=readme-ov-file#environment-setup) but when trying to run a script, getting error like this - ![image](https://private-user-images.githubusercontent.com/14244685/346326853-5ba0d60e-2c89-4300-a6cb-f53f80a35b59.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNjgzMjgsIm5iZiI6MTcyMDM2ODAyOCwicGF0aCI6Ii8xNDI0NDY4NS8zNDYzMjY4NTMtNWJhMGQ2MGUtMmM4OS00MzAwLWE2Y2ItZjUzZjgwYTM1YjU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE2MDAyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliZjZhZjAwMjJlYWViZTUwNDRjZmNiNjQ3NWNiNmM1MDFiMWEzNDkyZGY4Yzg4N2ZmMjBjNTQyNzFhY2QzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rAOHbRptz5sWu1Q1Q1SZ7cPFIZY0gk_h3A0vyoz21k8)
> 
> This issue seems it will take some time. Thus I want to work on it later.

@mhmohona I think scribe_data wasn't successfully installed can you do `pip install scribe_data` and see?

**Comment by andrewtavis** [comment]
Ah ya, good point @Jk40git. It's not picking up Scribe-Data in your environment 🤔 We can maybe check this with a `pip install .` before the next release and figure out where the path issues are? 

@Jk40git, you could also check this and @mhmohona could review? As you two see fit :)

**Comment by andrewtavis** [comment]
Specifically what we're looking for is if a person on Windows does the following:

```
pip install .
scribe-data q -all
```

If the data starts being downloaded, then that's the first hint that things are working properly :)

**Comment by Jk40git** [comment]
> Ah ya, good point @Jk40git. It's not picking up Scribe-Data in your environment 🤔 We can maybe check this with a `pip install .` before the next release and figure out where the path issues are?
> 
> @Jk40git, you could also check this and @mhmohona could review? As you two see fit :)
Okay sure I was able to access it before  the recent changes. But I will have a look at it again

**Comment by Jk40git** [comment]
> Specifically what we're looking for is if a person on Windows does the following:
> 
> ```shell
> pip install .
> scribe-data q -all
> ```
> 
> If the data starts being downloaded, then that's the first hint that things are working properly :)

Okay do you mean something like this?
![Uploading Screenshot 2024-07-07 223404.png…]()

**Comment by andrewtavis** [comment]
That's the top of the output where you copied both commands in one, right @Jk40git? Now that you have it installed, and please check that you've git pulled, can you show what the output of `scribe-data q -all` is?

**Comment by Jk40git** [comment]
> That's the top of the output where you copied both commands in one, right @Jk40git? Now that you have it installed, and please check that you've git pulled, can you show what the output of `scribe-data q -all` is?

Yes. the second output 
`bash: scribe-data: command not found`

**Comment by andrewtavis** [comment]
Hmmmm, but that's weird as it should have been covered by `git install .`. Is your local Scribe-Data up to date with `git pull`?

**Comment by Jk40git** [comment]
`git install .`? Or `pip install .`?

Yes it's up to date

**Comment by andrewtavis** [comment]
Sorry, `pip install .`. But this after `git pull` from the main branch here :)

**Comment by Jk40git** [comment]
That's what I did It says command not found

**Comment by andrewtavis** [comment]
Ok, well that's not good 😅 Can you tell us if you have the `cli 
` directory in your local version, so `src/scribe_data/cli`? @mhmohona, you're also on Windows, right?

**Comment by Jk40git** [comment]
> Ok, well that's not good 😅 Can you tell us if you have the `cli ` directory in your local version, so `src/scribe_data/cli`? @mhmohona, you're also on Windows, right?

Yes please I have the cli directory

![Screenshot 2024-07-09 160326](https://github.com/scribe-org/Scribe-Data/assets/125589910/410c1187-ea8b-45c6-96fb-2d935cfef174)

**Comment by andrewtavis** [comment]
Thank for the conversation here, @Jk40git! Just checking things with the questions, hope you understand :) This is definitely something need need to be looking into then, as it seems that the CLI isn't being installed for you. @mhmohona, it'd be great to get your feedback as I believe it's working on your end, but maybe I'm misremembering your operating system as Windows, or there could be something else going on 🤔

@Jk40git, specifically [this line in setup.py](https://github.com/scribe-org/Scribe-Data/blob/64eb52b0be2d4fe7d9f212d733c602463c79046d/setup.py#L50) is the one that is setting up the CLI on install. It's at least worked for @mhmohona and I 🤔 I'm wondering what some potential fixes could be?? The line in question is:

```python
  "console_scripts": [
      "scribe-data=scribe_data.cli.main:main",
  ],
```

Maybe something that's going on is that we have a prior version that's installed and the new one isn't being picked up? So maybe @Jk40git you could try `pip uninstall scribe-data;  pip install .` as a way of reinstalling the package?

If this does work for you, then something we'd need to make sure of is that the old version of things is removed when a person wants to install the new version :) Generally I think that [this comment and the thread it's in](https://github.com/pypa/pip/issues/9110#issuecomment-723662573) should have most of the answers we're looking for. Things to try:

1. Uninstall and reinstall

```bash
# Solution I suggested above
pip uninstall scribe-data
pip install .
```

2. Force reinstall

```bash
# Should behave as the above
pip install --force-reinstall scribe-data
```

3. Update the `entry_points` and `console_scripts` via the egg info

```bash
python setup.py egg_info
```

@Jk40git, can you try the above and let us know if `scribe-data q -all` works on your end?

If one of these works, we should definitely add a quick line about them into the readme and contributing guide!

**Comment by Jk40git** [comment]
It output this 
![Screenshot 2024-07-09 212845](https://github.com/scribe-org/Scribe-Data/assets/125589910/d4e38689-1df8-4bc2-b4cc-b6b2b1337204)

**Comment by andrewtavis** [comment]
Ah this is at least some progress :) What command fixed it for you, @Jk40git? You could do a PR to add it to the readme and contributing markdown files in the installation sections?

**Comment by andrewtavis** [comment]
And what I'm seeing above is that specifically the paths are not being computed correctly for Windows 🤔 So at one point in `update_data.py` early on we're using `/` based paths, and because of that the CLI thinks the paths are invalid and we get no language - data type pairs to query data for. We can maybe update the docs and then find the spot where this problem is? We should definitely adopt pathlib as much as we can.

**Comment by Jk40git** [comment]
> Ah this is at least some progress :) What command fixed it for you, @Jk40git? You could do a PR to add it to the readme and contributing markdown files in the installation sections? If it's the first commands above, then maybe we can put the second as that's the first combined, so adding in the following:
> 
> ```
> # To install new functionality post updates:
> pip install --force-reinstall scribe-data
> ```
> 
> The above would help people after we get the next release out :) Feel free to send something along that you think would help people, @Jk40git!

okay sure. I did the steps above

``` shell
pip uninstall scribe-data
pip install .
```
`shell
python setup.py egg_info 
`

**Comment by Jk40git** [comment]
> Ah this is at least some progress :) What command fixed it for you, @Jk40git? You could do a PR to add it to the readme and contributing markdown files in the installation sections? If it's the first commands above, then maybe we can put the second as that's the first combined, so adding in the following:
> 
> ```
> # To install new functionality post updates:
> pip install --force-reinstall scribe-data
> ```
> 
> The above would help people after we get the next release out :) Feel free to send something along that you think would help people, @Jk40git!

 
At some point   `pip install --force-reinstall scribe-data` fails cause of the misbehavior of the PyICU.
But 
```  pip uninstall scribe-data  
     pip install .``` works fine

**Comment by andrewtavis** [comment]
Ok, ya that PyICU stuff will need to be figured out later ... Will be great when we have Dockerized deployments up that just package the whole thing! Let's keep this documentation in mind! 

@Jk40git, do you want to check and see where we have `/`s hardcoded?

**Comment by Jk40git** [comment]
Can you give more explanation or details. What am I supposed to change the `/` hardcoded to?

**Comment by andrewtavis** [comment]
You'd use `pathlib`, which is set up to use `/`s or `\` depending on operating systems :) So where you see a slash based URL, we should instead use pathlib.

**Comment by Jk40git** [comment]
> You'd use `pathlib`, which is set up to use `/`s or `\` depending on operating systems :) So where you see a slash based URL, we should instead use pathlib.

So I have to import pathlib right ?

**Comment by andrewtavis** [comment]
Yes that'd be the way. You can check how pathlib has already been used :)

**Comment by axif0** [comment]
hello.. @andrewtavis

**Comment by mhmohona** [comment]
Please assign @axif0 on this issue. I dont have any problem.

**Comment by andrewtavis** [comment]
Perfect, thank you both! I'll merge in the current PR from @Jk40git and then @axif0 can work on implementing further changes to the paths 😊

**Comment by andrewtavis** [comment]
I had some major rewrites to do so that we could get the translation process working, so I went ahead and did a ton of changes for this in aef7e5a. @axif0, do you want to try out some of the functionality on your machine and also check the code for cases where the paths are still hardcoded with "/" that are only valid for Linux/Mac? We want all paths to be derived via `pathlib.Path` :)

**Comment by andrewtavis** [comment]
At this point we're ready for people to actively start testing the new paths on Windows 😊 Can folks pull the current changes, install the current version with `pip install -e .` and then try some CLI commands to make sure they work out? We still have the problem with the PyICU dependency, but that should also be worked out soon!

**Comment by andrewtavis** [comment]
b82bb67 should close this up mostly :) Closing now and we can test all of this with the rest of the functionality before the v4.0 release 😊 Thanks all!
