### ISSUE TITLE
Check out how to add the GPL3.0 license to the tops of Scribe-Data files without having it displayed in the docs

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#128]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that's advised for GPL3.0 code is for a short license notice to be put at the top of each file such the copy left notice will be maintained even if the codebase and the file are separated. An issue with this for Scribe-Data is that the files are being used directly in the documentation, and we don't want to the license notice at the top of each page in the docs. One thing that came up in the recent sync is that maybe we can include HTML tags for a dropdown around the notice such that it's hidden in the docs unless someone opens it. Aside from this, it'd be great to see if we can automatically remove this somehow so the docs don't get overly messy...

If we can't figure this out, then we'll just not put the license at the top of files, which isn't advised, but is legally ok :)

### Contribution

Happy to work with someone on this and assist as needed!

**Comment by mhmohona** [comment]
So I asked chatgpt about it, and it suggested  that we can use custom css for doing this. Thats way, it will be only file, but will be hidden in doc.

**Comment by andrewtavis** [comment]
Thanks for looking into this, @mhmohona! Custom CSS how? Wouldn't we need a page element to hide? I'm not really sure where we'd get that from in a multi line Python comment, but definitely something to explore!

**Comment by andrewtavis** [comment]
Closed by d6d2127 :) Thanks for the suggestion here, @mhmohona! Worked like a charm to use custom CSS to hide the HTML comments within the docs! 😊
