### ISSUE TITLE
Create needed queries for Bangla

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#134]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create the needed Wikidata query service queries for Bangla, with specifically queries being made for nouns, verbs, prepositions, adjectives, and any other word type of interest. We can explore Wikidata a bit for this and decide what other word types would be good to include in the issue here :) Suggestions welcome!

A quick search is indicating that Bengali is the English name for Bangla, so work for this should go into [src/scribe_data/extract_transform/languages/Bengali](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/extract_transform/languages/Bengali). Separate directories for word types should be added, and queries for each based on those for other langauges and based on available data can be made 😊

### Contribution

Happy to support the work on this! 🚀

**Comment by mhmohona** [comment]
I would love to work on this issue!

**Comment by andrewtavis** [comment]
Assigned! Thanks @mhmohona 😊 Let us know your thoughts on what word types we should be doing!

**Comment by andrewtavis** [comment]
2f301d2 sent along a minor edit to remove the query comments, @mhmohona :) I think that having the info in the header as you had it makes sense, and specifically Scribe-Data developers and users are able to see what the QIDs and PIDs are in various ways. For users, if someone were to say use the query on [query.wikidata.org](https://query.wikidata.org/), then there are tooltips on hover to show the label. This functionality is also available in VS Code via the [Wikidata QID Labels](https://marketplace.visualstudio.com/items?itemName=blokhinnv.wikidataqidlabels) extension! If you're using VS Code, then I'd definitely suggest installing the extension, or if not we can look for another way of maybe getting them in :)

Thanks for this! ☀️
