### ISSUE TITLE
Update docs with file types and directory indicators

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#135]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in Saturday's sync, it would be good to have a more explicit definition of the paths within the documentation. If we are going to the documentation of a file, then it would be great to have the filetype appended to the end of the navigation, and if we're going to a directory, then it'd be great if the navigation had a `/` at the end :)

This issue would apply this throughout the docs. I'll send along two examples of each of the above. The way that it can be tested locally is to cd into the `docs` directory and then do `make html`, which is a command from [sphinx](https://www.sphinx-doc.org/en/master/usage/quickstart.html). From there, within `build/html` we can use [live server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) to open `index.html` by right clicking it (see below):

![Screenshot_2024-05-20 21 41 43](https://github.com/scribe-org/Scribe-Data/assets/24387426/cb13256e-1a15-4184-8576-71bb2148d480)

From there the local version of the docs will be opened in the default browser such that progress can be checked 😊

### Contribution

@lillian-mo indicated that this issue would be of interest 😊 Feel free to write in here and I'll assign!

**Comment by andrewtavis** [comment]
@lillian-mo, 06d109a includes the two base examples that I did in the sync, which I confirmed as working locally. Let me know if there's anything else I can do to support!

**Comment by andrewtavis** [comment]
Hey @lillian-mo 👋 Feel free to write in here so I can assign :) Also, I'll be doing the directory refactor today after all as I work through the current PR, but that should be done by EOD. I'll write in here when it's all done!

**Comment by andrewtavis** [comment]
All the directory reordering has gone through now, so we're good to go for this! :)

**Comment by andrewtavis** [comment]
Hey @lillian-mo 👋 Quick checkin on this :) Let me know if a call would help here! No stress if you're a bit busy 😊

**Comment by lillian-mo** [comment]
Hey! I’m super sorry for the delay, I can probably get this done bu the end
of next week. It’s currently midterm season so I’ve been falling behind a
lot. Super sorry again!

**Comment by andrewtavis** [comment]
No stress at all, @lillian-mo! Just checking in :) If it's midterms, then wait till they're done! And good luck! 🍀

**Comment by lillian-mo** [comment]
hey @andrewtavis super sorry about the delay! I should be able to get to this this weekend - I'll let you know if I need any help!

**Comment by andrewtavis** [comment]
Sounds perfect, @lillian-mo! Looking forward to the review! :)

**Comment by lillian-mo** [comment]
@andrewtavis thanks! I've changed some of the links, but I can't seem to push these changes as the html isn't part of the directory - how should I do that?

**Comment by andrewtavis** [comment]
Hey @lillian-mo! 👋 The changes should be going into the docs subdirectory here and then your changes would be reflected in there. So basically the `.rst` files, and then you can test it with the `make html` command from within the docs directory :) Hope this helps, and let me know if you'd like to chat about it!

**Comment by lillian-mo** [comment]
@andrewtavis super sorry for missing this! (also sorry for being super slow in general) Sounds good, will fix soon!

**Comment by andrewtavis** [comment]
No stress at all, @lillian-mo! Take your time, and thanks for the communication here!

**Comment by andrewtavis** [comment]
In progress via a recent discussion between @lillian-mo and I :) Let me know if any help's needed!

**Comment by andrewtavis** [comment]
Closed by #185 😊 Thanks so much for the help here, @lillian-mo!
