### ISSUE TITLE
Implement command structure for the CLI

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#136]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would implement a command structure for the CLI for Scribe-Data with the following commands:
- poll (check whether there is new data available)
  - Note: How would we check from when? Are we passing a date, or could we check it against a file?
- query (Get the most recent data based on poll)
- `--language` (`-l`)
- `--word-type` (`-wt`)
- `--output-file` (`-of`)
- `--output-tyle` (`-ot`)
- `--list-languages` (`-ll`)
  - list available lang codes
  - list available word types per lang
- `--help` (`-h`)
- `--version` (`-v`)
- `--update` (`-u`)

Based on the discussion in the sync, I think that it makes sense for us to stick with argparse as it's already being used in the codebase :)

Note that this issue is solely for implementing the commands themselves, with individual issues for functionality following from there! Note further that we need to chat directory structure and where these commands are being defined. I'll be reaching out to people on this 😊

### Contribution

Note that this issue is a part of GSoC 2024 and thus will be assigned to @mhmohona 🥳 Please write in so we can assign :)

**Comment by andrewtavis** [comment]
We can get started on this once #134 is done. Let's also include #125 for GSoC, but we can work on that later as we reimplement some things :)

**Comment by mhmohona** [comment]
I would like to work on this issue.

**Comment by andrewtavis** [comment]
Thanks @mhmohona! ☀️☀️

**Comment by mhmohona** [comment]
Here, for retrieving data, shall I do it from this folder - https://github.com/scribe-org/Scribe-Data/tree/main/language_data_export?

**Comment by andrewtavis** [comment]
Yes exactly, @mhmohona! The `formatted_data` directories have been moved out of the language folders, and in a bit we'll remove the `language_data_export` directory and replace it with what the user passes to the CLI :) Do you have an idea for the baseline file name? Maybe we can do something like `scribe_language_data_export` with the given languages and word types inside? But then they could of course choose their own name as well :)
