### ISSUE TITLE
Add pre-commit hooks and checks to the project

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#137]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would focus on adding in [pre-commit](https://pre-commit.com/) to Scribe-Data such that linting, formatting and other checks could be ran on commit to avoid them being sent to the repo. Directions on how to setup pre-commit would further need to be added to the readme and contributing guide :)

- Note that we also have another pre-commit issue in https://github.com/scribe-org/Scribe-iOS/issues/450

### Contribution

Would be happy to support or get to this as I can! This would also be a good first issue for someone who has some Python experience or experience setting up pre-commit 😊

**Comment by kush34** [comment]
Hey, this looks easy, I am working on this. can I ask if any help is needed?

**Comment by andrewtavis** [comment]
Hey @kush34 👋 Sure thing! Happy to help if you need :) You can checkout the pre-commit config file for another project I work on [here](https://github.com/activist-org/activist/blob/main/.pre-commit-config.yaml). Generally the thing to do is use `pre-commit sample-config > .pre-commit-config.yaml` that'll give us the file, and then from there we can add in the ruff hooks that are in the config file I linked. From there `pre-commit install`, and then we know it works with `pre-commit run --all-files` 😊

**Comment by andrewtavis** [comment]
You'd also be welcome to pick up the other issue we have for this - https://github.com/scribe-org/Scribe-iOS/issues/450 - once this one is finished!

**Comment by andrewtavis** [comment]
Closed via #141 :) Thanks for the help here, @kush34! Feel free to write in https://github.com/scribe-org/Scribe-iOS/issues/450 if you have interest in working on that one as well 😊
