### ISSUE TITLE
Implement `query` functionality within CLI

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#143]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would implement the `query` (`q`) functionality within the Scribe-Data CLI. Work for this is already being added in to #140 as the `query` command is being linked to the `update_data.py` process. A on the command setup is that we need the user to pass at least one of the following: `--all`, `--language` or `--word-type`, as without this the CLI wouldn't know what to get, and I don't think that it's wise to query everything without an explicit `--all` call :)

### Contribution

@mhmohona will be working on this as a part of GSoC 2024! As stated, #140 will likely close this :) @mhmohona, can you write in here so I can assign?

**Comment by mhmohona** [comment]
Working on it!
