### ISSUE TITLE
Implement `--output-dir` and `--overwrite` functionality for a JSON file output

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#144]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add in the `--output-dir` (`-od`) and `--overwrite` (`-o`) functionality to the Scribe-Data CLI. This will allow the user to specify a directory where the results of the `--query` command will be written. Note that I renamed this `--output-dir` from the discussed `--output-file` as if there's more than one output file, then the string provided will need to be to a directory. So as to avoid checks for if we're returning a file or a directory and issues that that would cause for the end users, let's always return a directory. Things this argument will do:

- Checks to make sure that the argument past is not a file type, warning if it is (i.e. we don't want `.json`, etc)
- Check if the directory already exists
- If it does exist, checks if the files to be generated are already present
  - If they do exist, then the value of `--overwrite` should be checked
    - If `false`, check if each file that already exists should be rewritten and skip queries if the user says no via `input()`
    - If `true`, then overwrite all files
- If it doesn't exist, then make the directory, run the queries and put the end files to the new directory

### Contribution

@mhmohona will be working on this as a part of GSoC 2024 ☀️ Please write in here if you would, and let us know if you need some support! 😊

**Comment by andrewtavis** [comment]
We also should discuss what the default export directory name is 🤔 I think there's value in branding it as it'll also make it easier for the lay user to find? `scribe_data_export`?

**Comment by mhmohona** [comment]
Yea, we can rename it to `scribe_data_export`.

**Comment by andrewtavis** [comment]
Hey @mhmohona 👋 FYI I'm realizing that it'd make sense to have file type based names for the export directories, as ultimately the JSON directory will still need to exist while sqlite directories are being created. Also makes the return and distinguishing between them a bit more easy. As seen in [the project root](https://github.com/scribe-org/Scribe-Data), we now have `scribe_data_json_export` and `scribe_data_sqlite_export`. Let me know if you think this makes sense!  We can also change it back later 😊

**Comment by mhmohona** [comment]
So I have worked on this issue, and its how getting the output - 

![image](https://github.com/scribe-org/Scribe-Data/assets/14244685/a93238d3-df79-4df0-8a14-2a049d3b245a)

Is it okay? How can I make an improvement on it?

**Comment by andrewtavis** [comment]
We can help on the output for this, @mhmohona, but as said on Matrix, let's include the length of the file :) Check the [line in the utils](https://github.com/scribe-org/Scribe-Data/blob/2b6eef41f9b3f2c81e374d620688c55ad7f3170e/src/scribe_data/utils.py#L302) for how the original output of `update_data.py` looks as well 😊

**Comment by andrewtavis** [comment]
For this one, @mhmohona, we need to convert Scribe-Data's CLI `query` command over to using `update_data.py`. Maybe we can do a call on this at some point to plan this out a bit better? I think that we have the basics of what's needed here, but remember that the goal is that we're brining down new data, not moving the data from [scribe_data_json_export](https://github.com/scribe-org/Scribe-Data/tree/main/scribe_data_json_export) as this file will eventually be removed 😊

**Comment by andrewtavis** [comment]
Thinking about this further, @mhmohona, as of now [scribe_data/wikidata/update_data.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/wikidata/update_data.py) is just a script that's ran via the command line. What likely needs to happen is that we need to put the code for that file into a function that we can then import into the [scribe_data/cli/query.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/cli/query.py) file :)

**Comment by mhmohona** [comment]
@andrewtavis,does this satisfy the requirement? 


![image](https://github.com/scribe-org/Scribe-Data/assets/14244685/f6ef2bf3-d50e-41c8-afaf-a657c17515a0)

**Comment by andrewtavis** [comment]
Looking really great, @mhmohona! I think that we're ready for a PR :)

**Comment by mhmohona** [comment]
I have pushed my changes on #163 as I forgot to switch branch before working. 😅

**Comment by andrewtavis** [comment]
Closed by #163 😊 Thanks for all the work here, @mhmohona! ☀️
