### ISSUE TITLE
Implement CLI query `.csv` and `.tsv` `--output-type` functionality via `convert`

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#146]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As discussed in the [24/5/2024](https://etherpad.wikimedia.org/p/scribe-dev-sync-2024-5-24) GSoC sync, we'd like Scribe-Data to be able to also export other file types besides JSONs. This issue would look into the exporting of `.csv` and `.tsv` files. The user would call `--ouput-type csv` or `--ouput-type tsv` (or `.csv`/`.tsv` just to be sure), and then the resulting JSON files would be converted over to `.csv`/`.tsv` files. To be more explicit, Scribe-Data would first export JSON files as that's the baseline output file type, and then the `convert` process would run such that these filetypes are converted over to the required filetypes. The files in `OUTPUT_DIR/German/` like `nouns.json` and `verbs.json` would be rewritten to `OUTPUT_DIR/German/nouns.csv`, etc.

- Note that this issue is blocked by #144
- Note further that the process to convert the JSON files over to CSVs and TSVs has not been written yet :)

### Contribution

@mhmohona will be working on this as a part of GSoC 2024! ☀️ Please write in here so I can assign, and let us know if there's anything we can do to support!

**Comment by mhmohona** [comment]
gonna work on it!

**Comment by andrewtavis** [comment]
Note that for this issue and #145 we should be using [scribe_data/cli/convert.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/cli/convert.py), with the functionality going in there. If a person wants to query from Wikidata and convert the output automatically, then the functions for convert should be running in the background 😊

**Comment by andrewtavis** [comment]
Closed by #163 :) Thanks so much, @mhmohona! ☀️
