### ISSUE TITLE
Generate data for autosuggest

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#15]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is for the creation of data for autosuggest for each Scribe keyboard. The process should mostly be language agnostic - the creation of a function that requires an input of a language or language abbreviation - with further steps that are language specific coming after the main function call. 

The goal is to generate dictionaries and then JSONs of common words and the most common words that follow them per language. This is more involved than using pre-trained packages like [wordfreq](https://github.com/rspeer/wordfreq/), but could be achieved through Wikipedia article data mining. Steps involved include:
- [x] Using Wikipedia dumps as in [wikirec](https://github.com/andrewtavis/wikirec#downloading) would allow us to analyze a random selection of articles (we'd need to determine the percentage needed)
- [x] We'd need to clean the articles down to just words as done in [wikirec](https://github.com/andrewtavis/wikirec#downloading) for non-BERT models
- [x] We'd then find the most common words in the new corpus
- [x] We'd then check what the three most common words found after these words are
- [x] We'd then create dictionaries with the most common words as keys and the most common words that follow them as values (these words would be used as suggestions for their respective keys)
- [x] Derive a reasonable size of article corpus from which autosuggestions can be generated
    - I'd say that 1,000,000 is a round max, as 1,000 autosuggestion combinations can be generated in roughly an hour
- [x] Derive the size of the needed autosuggest dictionary (we can do 1,000 for now)
- [x] Add a step to run [query_profanity.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/query_profanity.sparql) for the given language and remove words that are included in its results
- [x] Running the above process for all Scribe languages for a large enough corpus and uploading the results to project directories
- [x] Remove data path to Android and Desktop that don't receive data updates at this point
- [x] Uploading v2.0.0 to PyPi

### Contribution

I'll be working on this as the data portion of [Scribe-iOS/issues/194](https://github.com/scribe-org/Scribe-iOS/issues/194) :) Others are welcome to help!

**Comment by andrewtavis** [comment]
First step for this is getting a minimal pipeline running that gets a single Wikipedia dump file (there are usually many per dump), gets a few articles from the dump, cleans them, computes the most common words, and then creates the dictionary to check the output :)

**Comment by SaurabhJamadagni** [comment]
Hi @andrewtavis, I would love to help you out with this task. If you have any subtasks that I could help out with do let me know. Also I had one more request if you don't mind. Could you assign a review to me for the PRs that you make yourself for this issue? I could learn a lot from those too.

**Comment by andrewtavis** [comment]
All sounds good, @SaurabhJamadagni :) Let me walk you through the first commits that I make as they're tested for classes I've had and other packages, so there's no need for a review per say, and there really is going to be a LOT of code. Happy to present the ideas to you though 😊 We can then split the subtasks here, and can further discuss https://github.com/scribe-org/Scribe-iOS/issues/194 on a call :)

**Comment by SaurabhJamadagni** [comment]
Yup @andrewtavis, that sounds good! 😊

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, just FYI, to make all this easier I changed the scope of this to only get the three most common words. We can do other tweaks later on, but adding probabilities and such is not within scope of a minimum rollout - especially when this already will be quite good 😊

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, 729461b added the full process for autosuggestion generation based on Wikipedia :) I'm going to need to run the whole thing through with a larger number of articles, as till now I've just done 50 and found the five most common words and the three words that most commonly follow them. After that it's rinse and repeat for all seven languages. The main time constraint on all this will likely be downloading the dumps though.

I decided to do autosuggest updates via a [Jupyter Notebook](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/gen_autosuggestions.ipynb) so that we can go through and test on the articles if the cleaning process needs to be changed, or if we do things like remove certain words later on. Very happy to go through the codes with you at some point if you'd like 😊

**Comment by andrewtavis** [comment]
Happy to provide you with example JSONs within the iOS repo once we're done with autocomplete and are on to autosuggest :)

**Comment by andrewtavis** [comment]
Filtering out profanity by referencing [this repo](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words) might be good for autosuggest. I do think that it's necessary for autocomplete as if people want to swear, then they can, but it's likely not the best to suggest that they do it :)

**Comment by SaurabhJamadagni** [comment]
> Very happy to go through the codes with you at some point if you'd like 😊

Yes @andrewtavis, I would love to go through the code. Reading the comment is giving me an idea but its a bit fuzzy right now. Going through the code should help out a lot. I will also check out the commit soon. That should help understand a bit more too. Thank you 😊

**Comment by SaurabhJamadagni** [comment]
> Filtering out profanity by referencing [this repo](https://github.com/LDNOOBW/List-of-Dirty-Naughty-Obscene-and-Otherwise-Bad-Words) might be good for autosuggest. I do think that it's necessary for autocomplete as if people want to swear, then they can, but it's likely not the best to suggest that they do it :)
> 
> The ideality would be that this would come from Wikidata, and I've checked with the community to see if it's possible as of now.

Yeah that makes sense. I was curious how we would handle this. So is it possible directly from Wikidata?

**Comment by andrewtavis** [comment]
> So is it possible directly from Wikidata?

Someone from the community wrote back today about this. What it is that we'd do is query words from Wikidata and filter them using [Property:P6191 - language style](https://www.wikidata.org/wiki/Property:P6191), with what we're looking for being those that are linked to the following QIDs: [Q1521634 - vulgarism](https://www.wikidata.org/wiki/Q1521634), [Q545779 - perjorative](https://www.wikidata.org/wiki/Q545779) and [Q184439 - profanity](https://www.wikidata.org/wiki/Q184439) :)

So we need to add queries for these that will then be updated with the data update process here. In this way as new profane words are added or marked as such, we'll then be able to filter them here in the creation of the autosuggest options.

**Comment by andrewtavis** [comment]
I'll make an issue for this now, and we can go through the codes sometime this week or next, @SaurabhJamadagni 😊

**Comment by SaurabhJamadagni** [comment]
> I'll make an issue for this now, and we can go through the codes sometime this week or next, @SaurabhJamadagni 😊

Awesome, that sounds good! 😊

**Comment by andrewtavis** [comment]
@SaurabhJamadagni, we'd talked about going through the Python codes for this, so let me know if that's still of interest 😊 I'd be available for an impromptu call today and tomorrow evening :)

**Comment by SaurabhJamadagni** [comment]
Yes I am interested @andrewtavis. A call sounds good. Let's do one tomorrow evening. Does 17:00 UTC work for you?

**Comment by andrewtavis** [comment]
17 UTC's fine with me :) I'll send along an invite 😊
