### ISSUE TITLE
Docs update for all deployments

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#152]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Once #148, #149, #150 and #153 are done, it would be great to update the readme, contributing guide and docs with information about how a user can make use of the various Scribe-Data deployments :)

@mhmohona will be working on this as a part of GSoC 2024 ☀️ Happy to discuss the directions beforehand and help with reviewing them! Please write in the issue so I can assign :) :)

**Comment by mhmohona** [comment]
The mandatory doc update!

**Comment by andrewtavis** [comment]
Updated this with a reference to #153 as well 😊

**Comment by andrewtavis** [comment]
Closed by #180 🚀 Thanks so much, @mhmohona! 🙏
