### ISSUE TITLE
Documentation for CLI usage

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#165]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into documenting the commands for the Scribe-Data CLI. We'd need some of this to be on the [project readme](https://github.com/scribe-org/Scribe-Data/blob/main/README.md), and some of it to be within the [docs](https://github.com/scribe-org/Scribe-Data/tree/main/docs) 😊 Let's first discuss what's needed for this documentation, and from there implementation can start.

### Contribution

@mhmohona will be working on this as a part of GSoC 2024 ☀️ As always, would be great to have you write in here, and let me know what you're thinking on documentation! :)

**Comment by mhmohona** [comment]
Lets discuss about it in our next call.

**Comment by andrewtavis** [comment]
Sounds good, @mhmohona!

**Comment by andrewtavis** [comment]
Do you want to do a call before the sync for this, @mhmohona, or just spend say 15/20 minutes on it there?

**Comment by andrewtavis** [comment]
I think that generally the documentation is good here, @mhmohona! I'll close this one, but please let me know if there's anything else you had in mind and we can reopen. Other additions could also be post gsoc issues for the community 😊

**Comment by mhmohona** [comment]
@andrewtavis,so after adding adding version and upgrade commands,the documentation will need to be updated as well.

**Comment by andrewtavis** [comment]
Hey @mhmohona 👋 I actually added little bits about those commands to the USAGE.md file and the docs, so I think we generally should be good :) Let's not worry too much more about this during GSoC as we have a bit more coding and the blogpost(s) to focus on :) Maybe you could also draft some social messages too? 😊

**Comment by mhmohona** [comment]
I will
