### ISSUE TITLE
Add GIF of Scribe-Data usage to readme

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#179]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would add a GIF of how users can use the Scribe-Data CLI to the project's readme. From a dev sync, what should be included is:

- Total + query what was shown for total
- scribe-data list --languages
- scribe-data list --data-type
- scribe-data total -lang German -dt nouns -> "There are XYZ German nouns on Wikidata"
- scribe-data query -lang German -dt nouns -> Query of German nouns and saving the output locally
- scribe-data interactive -> Show workflow for something not yet focussed on

- Note that this is blocked by #142

### Contribution

Would be happy to work on this once we're a bit further along in GSoC or review a PR! 😊

**Comment by andrewtavis** [comment]
@axif0, do you want to be assigned here seeing as how you've already made some usage videos? We'd want this to wait just a bit so we're recording the more final version of the CLI, but would be great to get your support here :)

**Comment by axif0** [comment]
Ya definitely.

**Comment by andrewtavis** [comment]
Nice ok :) Still leaving this as blocked, but let's get to it in say mid November when things settle a bit more. Will be really important for when we let the Wikidata community know this is done 😊

**Comment by andrewtavis** [comment]
Unblocked, @axif0! Let us know what you think you'd like to include in this before making it :)

I'll send a message to the data channel now to ask for testing of the new formatting changes, but this can proceed while that happens 😊

CC @mhmohona 👋

**Comment by axif0** [comment]
I'm using [terminal-profile](https://github.com/pixegami/terminal-profile). Do you have any color preferences in mind? 

Demo-
![image](https://github.com/user-attachments/assets/5034fee9-4de3-46f6-8bd8-d580f2ea60ad)

**Comment by andrewtavis** [comment]
I'd say a dark mode terminal should be fine, and maybe one gif for list, total and get, and another gif for interactive mode?

**Comment by axif0** [comment]
Is this ok? Total 36 second. 


![List,Total and Get (3)](https://github.com/user-attachments/assets/f10218f6-9d10-4ae9-a540-d917712e8dbb)

**Comment by andrewtavis** [comment]
These are looking good, @axif0! Do you want to add them in to the readme and the docs? We can add a quick code block under them that has the commands as they're a bit quick, but if we have the commands that are used in a code block under them, then it should be understandable :)

**Comment by andrewtavis** [comment]
Closed by #516 😊 So happy to have these finally, @axif0! Really appreciate the care you put into them :)
