### ISSUE TITLE
function name upgrade() to upgrade_cli() in upgrade.py

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#188]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

In [main.py](https://github.com/scribe-org/Scribe-Data/blob/a072b52ba4ab627cf32714dd6587b0861ff1feb5/src/scribe_data/cli/main.py#L31) we import `upgrade_cli`, but in 
[upgrade.py](https://github.com/scribe-org/Scribe-Data/blob/a072b52ba4ab627cf32714dd6587b0861ff1feb5/src/scribe_data/cli/upgrade.py#L35) we called `upgrade()` is it .
For that i got error.
![image](https://github.com/user-attachments/assets/1d944581-66db-4159-a90b-a5e6f4a617bd)

**Comment by andrewtavis** [comment]
Hey @axif0 👋 Do you want to send along a PR for this?

**Comment by andrewtavis** [comment]
Thanks so much for the issue!

**Comment by andrewtavis** [comment]
Looks like @pamarthiabhinav already sent along a change 🚀 I'll check this later today :)

**Comment by axif0** [comment]
Ah ! already someone Already make an PR!

**Comment by axif0** [comment]
@andrewtavis, in version currently the message looks`Scribe-Data vScribe-Data v3.3.0 (Update available: vScribe-Data v3.0.1)\nTo update: pip scribe-data --upgrade` .

Shouldn't it look like `Scribe-Data v3.3.0 (Update available: v3.3.1)\nTo update: pip scribe-data --upgrade`

Can i work on this?

**Comment by andrewtavis** [comment]
Yes, @axif0, that makes sense :) You can also change `Update` to `Upgrade` :)

**Comment by andrewtavis** [comment]
Thank you!

**Comment by pamarthiabhinav** [comment]
@axif0 Apologies if you're working on this. But thanks for giving me a start for my contribution to the Scribe-Org.

**Comment by pamarthiabhinav** [comment]
@andrewtavis PR #189 is ready for review. Check it out!

**Comment by axif0** [comment]
@pamarthiabhinav it's ok. Chill. Welcome to Scribe-Org. We have a great mentor and you can learn a lot from him.
