### ISSUE TITLE
Modify Upgrade Message 

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#190]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

In Upgrade currently the message looks `Scribe-Data vScribe-Data v3.3.0 (Update available: vScribe-Data v3.0.1)\nTo update: pip scribe-data --upgrade` .

Shouldn't it look like `Scribe-Data v3.3.0 (Update available: v3.3.1)\nTo update: pip scribe-data --upgrade`
in [here](https://github.com/scribe-org/Scribe-Data/blob/a072b52ba4ab627cf32714dd6587b0861ff1feb5/src/scribe_data/cli/version.py#L59)
If it is. @andrewtavis  Can i work on this?

**Comment by andrewtavis** [comment]
Sounds good, @axif0! Feel free to change `Update` to `Upgrade` as well :)

**Comment by axif0** [comment]
@andrewtavis 
Should I add cli test cases for version check? if yes, then where should I add it?

I'll change the version message to `Scribe-Data v3.3.0 (Update available: Scribe-Data v3.3.1)\nTo update: pip scribe-data --upgrade`

**Comment by andrewtavis** [comment]
Closed by #191 🚀 Thank you for opening all of the issues today and getting to the fixes for them so quickly, @axif0! 😊
