### ISSUE TITLE
Make paths in test_check_query.py Windows compatible

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#197]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

This issue is to use pathlib to make all paths in [test_check_query.py](https://github.com/scribe-org/Scribe-Data/blob/d36ed210d52582374a09f3dbe741cf17de0a939e/tests/wikidata/test_check_query.py) compatible with Windows. We should check the way that the paths are made with pathlib in other parts of the project, and then we can implement such that the pytest tests will pass :)

Happy to assist with this and review when it's ready!

CC @axif0 :)

**Comment by axif0** [comment]
On it.. 🔥

**Comment by andrewtavis** [comment]
Closed by #198 🥳 Thanks for your hard work, @axif0! Really has been nice to have you more involved :)
