### ISSUE TITLE
--Interactive cli command error

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#200]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

Testing Interactive Cli command, I find the error. Is the command correct? 

![image](https://github.com/user-attachments/assets/ab95d156-ce53-47f8-ba7c-3ca0b1dd8ab2)

**Comment by andrewtavis** [comment]
There is at least one bug with interactive mode right now, @axif0, but as of yet no issue. Is this similar to what you were seeing, @mhmohona?

**Comment by mhmohona** [comment]
Thank you @axif0 for bringing it up. Yes @andrewtavis, its one of the errors. Submitting PR right away.

**Comment by andrewtavis** [comment]
Closed by #201 🚀 200 issues and PRs! Thanks so much for the fix, @mhmohona, and similarly for the issue to document the changes, @axif0 😊
