### ISSUE TITLE
Interactive cli issue

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#202]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

Seams like `Overwrite existing data without asking (y/n) [n]:` not working. May I know what it is for? 

![image](https://github.com/user-attachments/assets/db45b22d-4a14-460d-b512-be026f6aa1f7)

also `(a) for all languages` is occurring a bit of confusion for me :(

![image](https://github.com/user-attachments/assets/02f70934-712a-482e-ab12-ddcc7b990339)

**Comment by axif0** [comment]
I want to work on it, if it is not problem .

**Comment by andrewtavis** [comment]
CC @mhmohona for the discussion here :) The overwrite for existing data is to make sure that we're not overwriting already existing Scribe data if maybe the user needs it. And yes you can investigate the issues with `a`, @axif0!

**Comment by andrewtavis** [comment]
Post #204 we're quite close on the interactive functionality and the CLI in general. Can we take a look at `a` for all languages and data types here before we jump to #203? I think it'd be good for us to be able to say that it's stable and tested before jumping to making it fancier :)

**Comment by andrewtavis** [comment]
Let's make sure we can go through all of [USAGE.md](https://github.com/scribe-org/Scribe-Data/blob/main/USAGE.md) error free and then we can close this! I'll check it out a bit more over the weekend as well.

**Comment by andrewtavis** [comment]
Closed by #268 🚀 Great PR, @axif0!
