### ISSUE TITLE
Expand documentation outputs for Scribe-Data commands

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#208]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue would be to expand the [documentation of the Scribe-Data CLI](https://scribe-data.readthedocs.io/en/latest/scribe_data/cli.html) with the full updated outputs of the commands. Each command should be ran, and the full process of the command should be inserted into code blocks. The file to change the documentation can be found [here](https://github.com/scribe-org/Scribe-Data/blob/main/docs/source/scribe_data/cli.rst).

The documentation can be checked locally by:

```bash
# In local Scribe-Data director
cd docs
make html  # run makefile
```

And then you can open up the `docs/build/html/index.html` file to see the current local state of the documentation.

**Comment by siva224513** [comment]
i would like to work on this issue @andrewtavis

**Comment by andrewtavis** [comment]
Yes this would be a great one for you, @siva224513 :) Let me know if there's anything we can do to support!

**Comment by KesharwaniArpita** [comment]
Hi @siva224513 , Can I also contribute here?

**Comment by crocmons** [comment]
can I work on this issue @andrewtavis?

**Comment by andrewtavis** [comment]
Sure thing, @crocmons. @KesharwaniArpita, do you want to suggest a few changes you'd like to do, and now that you're more familiar we can also find further work to do that @crocmons can support with?

**Comment by KesharwaniArpita** [comment]
Yeah sure!!!

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis and @crocmons , do you think it would be helpful to start with the global commands and the list sub-commands? We would run each of the commands and insert the process and its output(or exemplary output) in the code blocks? Once we are done we can move to the sub-commands of get, total and convert?

Does this make sense?

@crocmons which one would you like to work on?

**Comment by andrewtavis** [comment]
Bringing in @mhmohona into this conversation as the original implementer of the docs :)

**Comment by andrewtavis** [comment]
Closing this as multiple PRs have expanded the CLI docs 🚀 Thanks all!
