### ISSUE TITLE
Render Jupyter notebooks inside the Scribe-Data documentation

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#210]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now the Scribe-Data documentation just presents a link to Jupyter notebooks as is seen on [readthedocs.io:scribe_data/wikipedia/gen_autosuggestions.html](https://scribe-data.readthedocs.io/en/latest/scribe_data/wikipedia/gen_autosuggestions.html). There is an option to render Jupyter notebooks in Sphynx documentation. This issue would add this functionality to our docs :)

### Contribution

This would be a great issue for someone to work on! Happy to answer questions, support as needed and review when a PR is up 😊

**Comment by AnishereMariam** [comment]
@andrewtavis, I'll pick this one up :)

**Comment by andrewtavis** [comment]
Thanks for your willingness to help, @AnishereMariam!

**Comment by andrewtavis** [comment]
Checking in with you here @AnishereMariam :) Do you need some support?

**Comment by AnishereMariam** [comment]
@andrewtavis, thank you for checking up. I have been able to fix this. I will raise a PR on it.

**Comment by andrewtavis** [comment]
Nice, @AnishereMariam! :)

**Comment by Khushalsarode** [comment]
shall we work this? @AnishereMariam

**Comment by AnishereMariam** [comment]
I have rendered the notebook. I am raising a PR on it. The bug slowed me down a bit but I can show you what I've done so far @Khushalsarode. Let's link up on Matrix

**Comment by Khushalsarode** [comment]
Sure

**Comment by andrewtavis** [comment]
Let us know if there's anything else we can do to support, @AnishereMariam! :)

**Comment by AnishereMariam** [comment]
Hi @andrewtavis, I raised a PR regarding this issue: #463. It was pretty challenging, lol. I would really appreciate your feedback on the PR.

**Comment by andrewtavis** [comment]
I think we're all done here for this initial issue. For further work we can make a new issue :) Let us know if you have suggestions, @AnishereMariam!
