### ISSUE TITLE
Add bash command for updating Unicode data to docs

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#211]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As of now [readthedocs:scribe_data/unicode/update_unicode_data.html](https://scribe-data.readthedocs.io/en/latest/scribe_data/unicode/update_unicode_data.html) doesn't have a code block example for its usage like [readthedocs:scribe_data/translation/update_words_to_translate.html](https://scribe-data.readthedocs.io/en/latest/scribe_data/translation/update_words_to_translate.html). This issue would add a code block to the first page that adds the command for the file docstring:

```bash
python3 src/scribe_data/unicode/update_unicode_data.py
```

**Comment by andrewtavis** [comment]
@mhmohona, I made this issue, but we should discuss how we actually want this commands to work in the future as the user is going to be potentially downloading from pip, so we'll then not have this path as we've had till now 🤔 Maybe some kind of way to pick up the location of the package?

**Comment by masembebrian** [comment]
hey @andrewtavis , can i kindly work on this?

**Comment by andrewtavis** [comment]
Unassigning so others can pick this up. Let us know if you still have interest, @masembebrian :)

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis, as per our earlier discussion, I removed all the translation files which I think has also broken this example link here https://scribe-data.readthedocs.io/en/latest/scribe_data/translation/update_words_to_translate.html . Can you help me find another example link?

**Comment by andrewtavis** [comment]
Closing this as this page has been deleted.
