### ISSUE TITLE
Create Scribe-Data Swahili data process queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#214]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create the queries for Swahili in the [src/scribe_data/language_data_extraction](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction) directory. To start we can make a nouns query and a verbs query in two separate PRs, and from there we can make new issues for other types of data. These queries can be based on the already existing queries for other languages 😊

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support and answer any questions that might come up in this process! Can also review when the PRs are up :)

**Comment by andrewtavis** [comment]
CC @@LevisNgigi who expressed interest in working on this :) Can you write in here and I'll assign? Feel free to make the directory structure as you see the other languages are structured!

**Comment by LevisNgigi** [comment]
Yes I can write in here. Yes I will make the directory structure as I have seen for other languages.

**Comment by andrewtavis** [comment]
Fantastic, @LevisNgigi! Looking forward to the contribution :)

**Comment by LevisNgigi** [comment]
Question, I am currently querying data from [Wikidata Query Service](https://query.wikidata.org/) and the column for singular and plural are currently empty for the swahili language.Is it possible to get clarification on how to proceed?

**Comment by andrewtavis** [comment]
Can you paste your query, @LevisNgigi? Maybe there's little data on Wikidata right now, or it's not categorized correctly 🤔 You can also try to remove everything from the query and just get Swahili words to check if there's info there :)

Nouns at the very least are usually consistent, so you'll still be able to send along your code that will work when there is data :)

**Comment by LevisNgigi** [comment]
SELECT DISTINCT
    ?lexeme
    ?lemma
    ?singular
    ?plural

WHERE {
    ?lexeme dct:language wd:Q7838 ;
        wikibase:lexicalCategory wd:Q1084 ;
        wikibase:lemma ?lemma .

    OPTIONAL {
        ?lexeme ontolex:lexicalForm ?singularForm .
        ?singularForm ontolex:representation ?singular ;
        wikibase:grammaticalFeature wd:Q110786 ;
    } .

    OPTIONAL {
        ?lexeme ontolex:lexicalForm ?pluralForm .
        ?pluralForm ontolex:representation ?plural ;
        wikibase:grammaticalFeature wd:Q146786 ;
    } .
}

LIMIT 100   
Above is my query. The lemma column has data but for singular and plural it is currently empty.Yes there are swahili words I had checked that before including the query with singular and plural.

**Comment by andrewtavis** [comment]
You can also use [src/scribe_data/check_language_data.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/check_language_data.sparql) to check the data totals :) It looks like there are 203 Swahili nouns using `Q7838` :)

**Comment by andrewtavis** [comment]
By the looks of it singulars and plurals haven't been added for them yet, which is ok 😊 When I started Scribe years ago so many languages had no data. French only had two verbs with conjugations, and now there are thousands. Can you convert the lexeme over to just the LID instead of the URI, and from there I think we should be good for now :)

**Comment by andrewtavis** [comment]
You can see the conversion in other queries :)

**Comment by LevisNgigi** [comment]
Yes just checked and they are only 203 and 20 verbs.Should I proceed or it needs more data?

**Comment by andrewtavis** [comment]
Proceed by all means, @LevisNgigi! There will be more data eventually :)

**Comment by LevisNgigi** [comment]
Thank you.Really appreciate your help.

**Comment by andrewtavis** [comment]
To [quote you](https://github.com/scribe-org/Scribe-Data/issues/178#issuecomment-2392909574): The pleasure is mine :)

**Comment by VNW22** [comment]
Hey, I would like to also work on this issue

**Comment by andrewtavis** [comment]
Hey @VNW22 👋 I think that @LevisNgigi has nouns covered. Would you want to make an adjectives query?

**Comment by VNW22** [comment]
yeah, happy to work on the adjectives query.

**Comment by GicharuElvis** [comment]
Hey @andrewtavis i would also like to work on this. Kindly let me know if there is anyway i could contribute.

**Comment by andrewtavis** [comment]
I'll leave it to the other contributors to say if there's more work to do here :) We'll make more issues soon.

**Comment by GicharuElvis** [comment]
Sure, no worries. I'll be on the lookout

**Comment by LevisNgigi** [comment]
> I'll leave it to the other contributors to say if there's more work to do here :) We'll make more issues soon.

I think we have the Nouns,verb and adjectives query.I think there is no more work here for now. @GicharuElvis

**Comment by GicharuElvis** [comment]
No worries. Let me have a look at the other issues. :)

**Comment by LevisNgigi** [comment]
Okay :). You can also check in Scribe-android. https://github.com/scribe-org/Scribe-Android

**Comment by andrewtavis** [comment]
Or for this we could also do an adverbs one or prepositions :) Not sure on that for Swahili, but could be something to look into 😊

**Comment by andrewtavis** [comment]
Hey all 👋 In regards to the Swahili work, I did some filtering for `sw` so it's Latin script as that's what a quick search showed is mostly used (sorry if this isn't the case!). Does it make sense to also make queries for the Arabic-letter style? And are there different names for these types of written Swahili?

**Comment by LevisNgigi** [comment]
Hey @andrewtavis the filtering you used works perfectly as the Swahili  that is written and spoken uses Latin script. The Arabic style of writing fizzled out with the coming of the missionaries who introduced Latin script. The Arabic-letter style is no longer in use .Also there are no other names for Swahili just that Swahili borrowed a lot from Arabic language hence the use of Arabic-letter style back in the day.

**Comment by andrewtavis** [comment]
Thanks for letting me know, @LevisNgigi!

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by LevisNgigi** [comment]
Sounds great let me have a look at them now.

**Comment by andrewtavis** [comment]
8b4fead was a needed fix here, @LevisNgigi :) The queries for adverbs and prepositions were still using the QID for adjectives, so because of that we were getting adjectives back for both. Check it out so you can see the difference!

**Comment by LevisNgigi** [comment]
Oh my bad, seems I forgot to change that. Thank you for correcting them. I really appreciate the work that you are doing considering all the issues that have popped up lately.

**Comment by andrewtavis** [comment]
Doing the best I can, and appreciate your support, @LevisNgigi!

**Comment by LevisNgigi** [comment]
Thank you.Pleasure is mine

**Comment by andrewtavis** [comment]
This is closed up now 😊 Thanks all so much for the hard work here!

**Comment by LevisNgigi** [comment]
Thank you so much for your help as well Andrew.

**Comment by andrewtavis** [comment]
Very welcome, @LevisNgigi :)

**Comment by VNW22** [comment]
@andrewtavis I hope its not to late, I was reviewing the adjective query that I worked on and I saw that there are forms that I did not include, I was hoping to expand the query.
Can I still do that?

**Comment by andrewtavis** [comment]
Yes, by all means, @VNW22! Really appreciate you going back through and expanding these :) We can do individual issues in the future as well 😊
