### ISSUE TITLE
Create Scribe-Data Yoruba data process queries

### ISSUE THREAD

**Issue by LevisNgigi** [scribe-org/Scribe-Data#217]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would create the queries for Yoruba in the [src/scribe_data/language_data_extraction](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction) directory. To start we can make a nouns query and a verbs query in two separate PRs, and from there we can make new issues for other types of data. These queries can be based on the already existing queries for other languages 😊

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support and answer any questions that might come up in this process! Can also review when the PRs are up :)

**Comment by andrewtavis** [comment]
CC @DeleMike, can you write in here so I can assign this to you?

**Comment by andrewtavis** [comment]
CC @AnishereMariam who also had interest in Yoruba and added a file for nouns in #215. Would we want to maybe have @AnishereMariam do nouns and @DeleMike can do verbs and other word types?

**Comment by AnishereMariam** [comment]
@DeleMike, I'd love to work together on this if you don't mind. If it's okay with you, I'll text you on Matrix for a detailed conversation on this issue.

**Comment by DeleMike** [comment]
@andrewtavis @AnishereMariam Sorry I took so long to reply. I was travelling but I'm set now!

It's okay and I'd love to work with you @AnishereMariam!

Yes @andrewtavis, I would do the verbs and other types. 

when would you like to have a sync @AnishereMariam ?

**Comment by andrewtavis** [comment]
Could those working here give an update of some work that could be done? We can find another issue if there's not much here, @AishatBolarinwa :)

**Comment by AishatBolarinwa** [comment]
Alright @andrewtavis Thank you

**Comment by AishatBolarinwa** [comment]
> [@andrewtavis](https://github.com/andrewtavis) , I'm currently waiting for [@AnishereMariam](https://github.com/AnishereMariam) to finish up the noun querys so I take it from there.
> 
> I would check in again to know what's the update on it. I don't want to override [@AnishereMariam](https://github.com/AnishereMariam)'s work.
> 
> [@AishatBolarinwa](https://github.com/AishatBolarinwa) , would you love to work on the `verbs` query? You could take that on. If you have questions just DM in the chat! :)

Okay, I'll be in your DM
Thank you

**Comment by andrewtavis** [comment]
Thanks for the directing, @DeleMike!

**Comment by AnishereMariam** [comment]
@AishatBolarinwa, your input is greatly welcomed. my PR for the noun query is here #215. Please review for further input. I send you a DM on matrix.

@DeleMike, we can start working on the verb query.

**Comment by MissTife** [comment]
@andrewtavis is there a way i can still join this project?

**Comment by DeleMike** [comment]
@AnishereMariam, many thanks. Could you work directly with @AishatBolarinwa on the verbs query, please?

**Comment by andrewtavis** [comment]
I'll also take a moment sometime tomorrow to make some more issues, all :)

**Comment by DeleMike** [comment]
@MissTife one suggestion, you could look into adjectives query, maybe? You can dm me if you want more explanations?

**Comment by MissTife** [comment]
> @MissTife one suggestion, you could look into adjectives query, maybe? You can dm me if you want more explanations?

Oh yes I will be happy to.

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Nouns are done via @AnishereMariam - review coming soon! - and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by KesharwaniArpita** [comment]
Hey @DeleMike can I also help out here?

**Comment by andrewtavis** [comment]
Nouns PR was brought in, right? Also included some Japanese work it memory serves me. Any other support that you all need?

**Comment by DeleMike** [comment]
Yes, you are right @andrewtavis . I just pulled. @KesharwaniArpita, if no one is working on the issue, you can create a PR to add the `verb` query for the Yoruba Language :)

Else, we can talk about how you could improve the language's data extraction module with nice additions like `adjectives` and `adverbs` queries.

**Comment by andrewtavis** [comment]
Sending along a prepositions query shortly to close this up given that we're centralizing the emoji process in #379 :) Thanks all for the hard work! 😊
