### ISSUE TITLE
Create Scribe-Data Ibibio data process queries

### ISSUE THREAD

**Issue by Ekikereabasi-Nk** [scribe-org/Scribe-Data#218]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue aims to develop queries for Ibibio in the `src/scribe_data/language_data_extraction` directory. Initially, we can create a query for nouns and a separate query for verbs. Following that, we can generate new issues for additional types of data. These queries can be modeled after the existing queries for other languages

Data types to include:
- [ ] Nouns
- [x] Verbs
- [ ] Adjectives
- [ ] Adverbs
- [ ] Prepositions
- [x] Emoji keywords

### Contribution

Feel free to reach out if you have any questions or need help along the way—I'm here to lend a hand!

**Comment by andrewtavis** [comment]
Thanks for this, @Ekikereabasi-Nk! Would you like to work on this?

**Comment by Ekikereabasi-Nk** [comment]
Yes @andrewtavis I will love to work on it. But I want to started with any of "Expand [language] verbs query". Thank you

**Comment by andrewtavis** [comment]
Assigning you to reserve this issue for you, @Ekikereabasi-Nk :) I'll make the adjectives query issue now 😊

**Comment by andrewtavis** [comment]
See #242, @Ekikereabasi-Nk :)

**Comment by Ekikereabasi-Nk** [comment]
@andrewtavis Alright

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) We can maybe keep an eye on the data here, @Ekikereabasi-Nk, and then work on things when more data is included? Have we ran the query to check for total data yet?

**Comment by andrewtavis** [comment]
Feel free to send along some queries that you're seeing as not being there, @Otom-obhazi. We found that there's not much data, but we can still write the base queries :)

**Comment by andrewtavis** [comment]
I just checked and ultimately there's no data for Ibibio at this point, so I think it's best if we close this and rework it later when there is data 😊

**Comment by Otom-obhazi** [comment]
no problem
