### ISSUE TITLE
Encountering IncompleteRead exception when making HTTP requests

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#219]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

IncompleteRead error occurred when I was trying to query data from Wikidata using the SPARQLWrapper library. If I try all languages along with data-type it causes me the error in interactive mode.

![image](https://github.com/user-attachments/assets/1d824117-697b-4679-a40f-b6e797b4689a)

I'll be working on this. pr on the way.

**Comment by andrewtavis** [comment]
Closed by #221 😊 Thanks for the issue and the work here, @axif0!
