### ISSUE TITLE
Expand Basque verbs query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#222]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Basque/verbs/query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Basque/verbs/query_verbs.sparql) file with as many conjugations as are possible from the current verbs on Wikidata. We can use code for getting verbs from other languages, and from there we can check Basque verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain conjugations as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

### Contribution

Happy to support with this and answer any questions I can! Also happy to review 😊

**Comment by KesharwaniArpita** [comment]
@andrewtavis, I have started working on this, Can I be assigned?

**Comment by andrewtavis** [comment]
Closed by #241 🚀 Well done, @KesharwaniArpita! Great to have you in the community 😊

**Comment by KesharwaniArpita** [comment]
Thank you so much @andrewtavis for your support🥺.
