### ISSUE TITLE
Expand Bokmål verbs query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#223]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Bokmål/verbs/query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Bokmål/verbs/query_verbs.sparql) file with as many conjugations as are possible from the current verbs on Wikidata. We can use code for getting verbs from other languages, and from there we can check Bokmål verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain conjugations as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

### Contribution

Happy to support as I can and answer any questions that come up! I'll be happy to review as well when the PR is up :)

**Comment by VNW22** [comment]
hey, would like to work on this issue.

**Comment by andrewtavis** [comment]
Thanks for your willingness to work on another issue, @VNW22!

**Comment by andrewtavis** [comment]
For now closed by #284 :) We'll check this later and add in more data as it's added and more properties are included :)

**Comment by andrewtavis** [comment]
Thanks so much for the work here, @VNW22!

**Comment by VNW22** [comment]
@andrewtavis I'll also expand the verbs querry that I did here :)

**Comment by andrewtavis** [comment]
Thanks, @VNW22!

**Comment by VNW22** [comment]
Heyy @andrewtavis, i need some assitance here. 
so i'm trying to run the code below;
SELECT 
  (REPLACE(STR(?lexeme), "http://www.wikidata.org/entity/", "") AS ?lexemeID) 
  ?infinitive ?masculineForm ?feminineForm ?neuterForm ?singularForm ?pluralForm
WHERE {
  ?lexeme dct:language wd:Q25167;
          wikibase:lexicalCategory wd:Q24905;
          wikibase:lemma ?infinitive.

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculine.
    ?masculine ontolex:representation ?masculineForm;
      wikibase:grammaticalFeature wd:Q499327.  
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?feminine.
    ?feminine ontolex:representation ?feminineForm;
      wikibase:grammaticalFeature wd:Q1775415.  
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?neuter.
    ?neuter ontolex:representation ?neuterForm;
      wikibase:grammaticalFeature wd:Q1775461. 
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?singular.
    ?singular ontolex:representation ?singularForm;
      wikibase:grammaticalFeature wd:Q110786.  
  }

  OPTIONAL {
    ?lexeme ontolex:lexicalForm ?plural.
    ?plural ontolex:representation ?pluralForm;
      wikibase:grammaticalFeature wd:Q146786.  
  }
}
but it returns "Server error: Unexpected end of JSON input"
but when I introduce LIMIT 10, the query works. Do I include the LIMIT function or how should I go about solving this?

**Comment by andrewtavis** [comment]
You should break the query up into smaller queries :)

**Comment by VNW22** [comment]
okay, thanks

**Comment by andrewtavis** [comment]
Very welcome :)

**Comment by andrewtavis** [comment]
It's under Norwegian now :)
