### ISSUE TITLE
Expand Czech data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#224]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Czech](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Czech) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Czech data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support with this and answer questions! I'd also be happy to review the PR for this when it's up :)

**Comment by OkpePhillips** [comment]
Hi Andrew,
Could you assign this to me? I have been researching the various verbal features of this language and I think I am ready to work on it.
Thanks

**Comment by andrewtavis** [comment]
Thanks for the research and picking this up, @OkpePhillips!

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by andrewtavis** [comment]
Closed by #377 :) Thanks all for the hard work!
