### ISSUE TITLE
Expand Danish verbs query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#225]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Danish/verbs/query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Danish/verbs/query_verbs.sparql) file with as many conjugations as are possible from the current verbs on Wikidata. We can use code for getting verbs from other languages, and from there we can check Danish verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain conjugations as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

### Contribution

Happy to support as I can with answers to questions as well as code review once the PR is up!

**Comment by catreedle** [comment]
Hi @andrewtavis, I would like to work on this issue :)

**Comment by andrewtavis** [comment]
Sounds great, @catreedle! I'll check the PR later :)

**Comment by andrewtavis** [comment]
Closed by #249 😊 Thanks so much, @catreedle! 🚀
