### ISSUE TITLE
Expand Esperanto verbs query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#226]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Esperanto/verbs/query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Esperanto/verbs/query_verbs.sparql) file with as many conjugations as are possible from the current verbs on Wikidata. We can use code for getting verbs from other languages, and from there we can check Esperanto verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain conjugations as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

### Contribution

Happy to support as I can via answering questions and reviewing the resulting code 😊

**Comment by Innocentefea** [comment]
I want to work on this task can you assign it to me.

**Comment by MissTife** [comment]
@andrewtavis Am I alloweed to work on this, I can see it has not been assigned yet?

**Comment by andrewtavis** [comment]
It looks like @KesharwaniArpita already has a PR up for this. We'll make more issues soon!

**Comment by andrewtavis** [comment]
I'm thinking we're generally good here, @KesharwaniArpita, at least for now 😊 Feel free to continue to look into other languages and and projects!
