### ISSUE TITLE
Expand Estonian data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#227]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Estonian](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Estonian) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Estonian data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support via answering questions and also reviewing code once a PR has been made 😊

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I'm interested in this. I will also like the create an issue for polish adjective extraction query

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by andrewtavis** [comment]
No stress, @Ekikereabasi-Nk!

**Comment by andrewtavis** [comment]
Ok, @Ekikereabasi-Nk :) So, for the verbs query here I've mapped out sections that would be good to split things into. This query will likely also need to be split into other files, but my suggestion would be to write the whole thing and then split it. I can also assist more here, but if you'd like to work on the verbs query more you'd be welcome to!

**Comment by andrewtavis** [comment]
Let's take what we've learned from the recent PRs and move on to verbs, @Ekikereabasi-Nk :) One thing, please pull the changes of main from time to time. I'm realizing that your branch is behind main, and it means that when I'm in your branch I can't check what the others have done.

**Comment by Ekikereabasi-Nk** [comment]
Thank you @andrewtavis.

**Comment by andrewtavis** [comment]
The verbs query still needs work here, but for now I think we're fine to close this and expand it later as needed by users. Thanks, @Ekikereabasi-Nk!
