### ISSUE TITLE
Expand Kurmanji data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#229]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Kurmanji](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Kurmanji) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Kurmanji data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support the development and review when the PR is up 😊

**Comment by Khushalsarode** [comment]
@andrewtavis I will work on this!

**Comment by andrewtavis** [comment]
Thanks for picking it up, @Khushalsarode! Let us know if you need any support :)

**Comment by Khushalsarode** [comment]
![wikidata](https://github.com/user-attachments/assets/c8d4a991-dab4-441d-8965-047af591845f)
@andrewtavis 
singulars

**Comment by Khushalsarode** [comment]
@andrewtavis would you like me to work on Marathi entity verbs/prepositions on wikidata?

**Comment by andrewtavis** [comment]
That's kind of up to you, @Khushalsarode :) If you'd like to expand them, then that would be really cool! I'm not sure if we can count Wikidata edits for Outreachy or Hacktoberfest, but if you're interested in editing a bit, then by all means!

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by Khushalsarode** [comment]
Thanks! 
Can I work on German and Italian data query language, or should I go one by one.
Kind of feel I can do both with ease!
@andrewtavis

**Comment by andrewtavis** [comment]
Let's check the other data types above to see if there is available data, @Khushalsarode :) Thanks for your efforts here!

**Comment by Khushalsarode** [comment]
@andrewtavis already on it! 
I think this language data entities arequite less in amount.

**Comment by andrewtavis** [comment]
Yes sadly, but we can still map out the queries for what's there as the data will be there eventually :)

**Comment by andrewtavis** [comment]
Closing this up @Khushalsarode as the plan in #379 is to centralize the emoji data needed. Sending a commit along with the `__init__.py` for it :)
