### ISSUE TITLE
Expand Latin data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#230]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Latin](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Latin) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Latin data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs #444 
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support the work for this as I can :) Can answer questions and also review the PR when it's finished 😊

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis , Can I be assigned this issue?

**Comment by andrewtavis** [comment]
Sure thing, @KesharwaniArpita! Let us know if there's something we can do to support :)

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by axif0** [comment]
if @KesharwaniArpita  don't mind, I want to work with latin pronouns.

**Comment by KesharwaniArpita** [comment]
By all means @axif0. It's always great to collaborate. ☺️

**Comment by andrewtavis** [comment]
@axif0, maybe also send along the adverbs and the prepositions, and then @KesharwaniArpita can finish the verbs?

**Comment by KesharwaniArpita** [comment]
Yup, sounds good to me

**Comment by Nowshin1077** [comment]
Hi, @KesharwaniArpita and @axif0 if you guys are ok then can I make a PR for Latin "Adverb" and "Preposition"? 😬 
My queries are working properly.

**Comment by andrewtavis** [comment]
Closing this so the remainder of the work can happen in #444 :)
