### ISSUE TITLE
Expand Malayalam data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#231]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Malayalam](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Malayalam) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Malayalam data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support by answering questions or reviewing when the PR's up for this!

**Comment by Kehindeadebisi** [comment]
Hi @andrewtavis, could you please assign this issue to me?

**Comment by andrewtavis** [comment]
Sure thing, @Kehindeadebisi! Let us know if you need any support :)

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by andrewtavis** [comment]
I guess we can add in an emoji keywords file, @Kehindeadebisi, but I'm also not sure what kind of emoji support Unicode would have for Malayalam 🤔 Does Malayalam have postpositions as well as prepositions? Can you check that and if so do a PR for that as well :)

**Comment by Kehindeadebisi** [comment]
@andrewtavis  Malayalam does have postpositions, though the query generated few results. I have raised a [pr](https://github.com/scribe-org/Scribe-Data/pull/316). On the emoji keywords, I'll work on it once I confirm Unicode support for Malayalam emojis

**Comment by andrewtavis** [comment]
Sounds great, @Kehindeadebisi! :)

**Comment by Kehindeadebisi** [comment]
@andrewtavis please check this[commit](https://github.com/scribe-org/Scribe-Data/commit/30fe2f524e67b37cf1bc0eddf488ac575e6a9c28) for the emoji keywords, am I on track please? The python file generated the output  in the json file. I basically went through the implementation of the other languages and tried to replicate

**Comment by andrewtavis** [comment]
I'll check this tomorrow, @Kehindeadebisi. At work right now and have plans for this evening :)

**Comment by andrewtavis** [comment]
Also done now! Amazing work, @Kehindeadebisi! 😊

**Comment by andrewtavis** [comment]
Maybe we can look into the other language directories and try to find one that we haven't made one of these larger issues for? :)
