### ISSUE TITLE
Expand Norwegian Nynorsk verbs query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#232]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Nynorsk/verbs/query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Nynorsk/verbs/query_verbs.sparql) file with as many conjugations as are possible from the current verbs on Wikidata. We can use code for getting verbs from other languages, and from there we can check Nynorsk verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain conjugations as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

- Note that a lot of the work here can be used for or based on work for #223

### Contribution

Happy to support via a review and also review the PR when it's been opened 😊

**Comment by catreedle** [comment]
Hi @andrewtavis, I would like to work on this issue.

**Comment by andrewtavis** [comment]
Sure thing, @catreedle! Please let us know if there's anything we can do to help :) Also FYI, I just corrected the link to the query above :)

**Comment by andrewtavis** [comment]
Closed by #247 🚀 Thanks so much for the attention to detail, @catreedle!
