### ISSUE TITLE
Expand Polish data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#233]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Polish](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Polish) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Polish data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support with this issue as needed and review when there's a PR open for it 😊

**Comment by Ekikereabasi-Nk** [comment]
Hi, @andrewtavis you can also assigned this to me. I have gotten a lot a knowledge from the community. Though I'm working on Ibibio right now, there is not much lexemes and lexical categories for ibibio on wikidata

**Comment by andrewtavis** [comment]
I think this makes sense, @Ekikereabasi-Nk! Hopefully there's more data here and we can also get more for Ibibio in the coming months :)

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by andrewtavis** [comment]
Do you want to look into some of the other queries for Polish, @Ekikereabasi-Nk? There are some good examples now for adjectives, adverbs and prepositions :)

**Comment by Ekikereabasi-Nk** [comment]
Sure @andrewtavis I will work on these "adjectives, adverbs, prepositions and Emoji keyword "

**Comment by andrewtavis** [comment]
Sounds great, @Ekikereabasi-Nk. Looking forward to the contribution :)

**Comment by Nowshin1077** [comment]
Hi @Ekikereabasi-Nk, I am adding adjectives, adverbs, and preposition queries. I hope you will not mind 😊

**Comment by andrewtavis** [comment]
Closed by #457 :) There's still work to be done on adjectives and adverbs, but this can be done later 😊
