### ISSUE TITLE
Expand Slovak data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#234]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Slovak](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Slovak) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Slovak data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support via a review and also answer any questions that come up during the work 😊

**Comment by shrutikamahale** [comment]
Hi @andrewtavis I am looking forward to contributing.. can you assign this issue to me?

**Comment by andrewtavis** [comment]
Looking forward to the contribution, @shrutikamahale! I just updated the link to the query above, btw :)

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by Otom-obhazi** [comment]
can i be assigned this??

**Comment by andrewtavis** [comment]
Thanks for your interest here, @Otom-obhazi! Let us know if we can do anything to assist :)

**Comment by Otom-obhazi** [comment]
please reassign me

**Comment by andrewtavis** [comment]
Hi @Otom-obhazi 👋 Replying to your email here :) One thing to look into is the queries that the others have made for other languages. We're working in the [src/scribe_data/language_data_extraction/Slovak](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Slovak) directory, and let's work on a new query for Slovak adjectives. We can check a query for other languages like the [Italian adjectives query](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Italian/adjectives/query_adjectives.sparql). Copy that query and try it out at [query.wikidata.org/](https://query.wikidata.org/), and then try the same query with `Q9058`, which is the Wikidata identifier for Slovak, instead of `Q652`, the Wikidata identifier for Italian. If all works well, you can send the query for Slovak adjectives along in the [src/scribe_data/language_data_extraction/Slovak](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Slovak) directory in an `adjectives` directory, so the final file will be  `src/scribe_data/language_data_extraction/Slovak/adjecives/query_adjectives.sparql`.

Let me know if you have further questions!

**Comment by Otom-obhazi** [comment]
when I run it, it shows no match record found.

**Comment by andrewtavis** [comment]
You used the wrong language id in your query, @Otom-obhazi :) It needs to be `Q9058`, not `Q1051`. Can you fix that and then send along a PR?

**Comment by Otom-obhazi** [comment]
https://github.com/scribe-org/Scribe-Data/pull/362

I did for adverbs.. it runs well

**Comment by andrewtavis** [comment]
Circling back to the adjectives, @Otom-obhazi: There are a lot of forms on the adjectives that weren't returned by the query. Could you check the other adjectives queries and find one that's returning more than just the adjective, but also other forms? From there you can then edit your Slovak adjectives query to return the forms that you're seeing on the items on Wikidata. Happy to explain more if you need some help :)

**Comment by Otom-obhazi** [comment]
Thanks, I'll check them out.

**Comment by andrewtavis** [comment]
Given the current data, this issue's all closed out. Thanks all for the work here!
