### ISSUE TITLE
Expand Tamil data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#236]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Tamil](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Tamil) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Tamil data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to answer any questions that come up in development and review a PR once one is open 😊

**Comment by siva224513** [comment]
I would like to work on this issue @andrewtavis

**Comment by andrewtavis** [comment]
Sounds good, @siva224513! Let us know if there's anything we can do to help :)

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by VNW22** [comment]
@andrewtavis can I work on this issue? and @siva224513 Can we work on this together?

**Comment by andrewtavis** [comment]
Sounds good, @VNW22 :) @siva224513, do you have a query set that you'd like to open a PR for here? Then @VNW22 will know which ones to work on. For now @VNW22, just maybe start with emoji keywords and prepositions :)

**Comment by VNW22** [comment]
@siva224513  if you need any help with the rest of the queries, feel free to reach out—I’d be happy to assist!

**Comment by andrewtavis** [comment]
Looks like this is all finished or at least to a base level. We can do further work in new issues 😊 Thanks all for the hard work!

**Comment by VNW22** [comment]
> Looks like this is all finished or at least to a base level. We can do further work in new issues 😊 Thanks all for the hard work!

I was looking into expanding the verb query for this language :)
