### ISSUE TITLE
Expand Ukrainian data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#237]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Ukrainian](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Ukrainian) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Ukrainian data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support with answers to questions and reviewing a PR eventually 😊

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis can I start with this first before I proceed to work on the "Create Scribe-Data Ibibio data process queries"

**Comment by Collins-Webdev** [comment]
> ### Terms
> * [x]  I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
> * [x]  I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)
> 
> ### Description
> This issue would look into expanding the [src/scribe_data/language_data_extraction/Ukrainian/verbs/query_verbs.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Ukrainian/verbs/query_verbs.sparql) file with as many conjugations as are possible from the current verbs on Wikidata. We can use code for getting verbs from other languages, and from there we can check Ukrainian verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain conjugations as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)
> 
> ### Contribution
> Happy to support with answers to questions and reviewing a PR eventually 😊


**Hi @andrewtavis**  
I’m Collins HAYA, an Outreachy contributor, and I’m interested in expanding the Ukrainian verbs query (#237). I’ve got experience working with language data extraction and would love to contribute by adding more conjugations from Wikidata. Could you assign me this task? I’m ready to get started!

**Comment by andrewtavis** [comment]
Thanks for your interest in helping, @Collins-Webdev!

**Comment by Collins-Webdev** [comment]
> Thanks for your interest in helping, @Collins-Webdev!

Thanks for assigning the project @andrewtavis . I’ll get started and keep you updated if anything comes up.

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by Kehindeadebisi** [comment]
@andrewtavis could you please assign this to me?

**Comment by Collins-Webdev** [comment]
> @andrewtavis could you please assign this to me?

Hello @Kehindeadebisi , @andrewtavis 👋🏼
Sorry, I am already working on this one.

**Comment by Kehindeadebisi** [comment]
> Hello @Kehindeadebisi , @andrewtavis 👋🏼 Sorry, I am already working on this one.

oh alright, that's fine. Just wanted to check open issues first, well done!

**Comment by andrewtavis** [comment]
Hey @Collins-Webdev 👋 For these issues we're allowing more than one person to be assigned. Could you let us know which queries you're working on and maybe @Kehindeadebisi can work on another one? :)

We don't need emoji keywords anymore as well as this functionality is being centralized, so that's been updated in the list 😊

**Comment by Collins-Webdev** [comment]
understood 👍🏼, @andrewtavis .
I am done with verbs. I am currently working on adverbs and nouns.

**Comment by andrewtavis** [comment]
Feel free to open up a PR with the first query so we can check it :)

**Comment by Collins-Webdev** [comment]
Hey @andrewtavis 👋🏼,
 I made the PR here : https://github.com/scribe-org/Scribe-Data/pull/424

**Comment by andrewtavis** [comment]
Thanks for the great work here, @Collins-Webdev :) Please feel free to check other language issues and see if you can support others with their languages 😊

**Comment by Collins-Webdev** [comment]
Thank you so much for the kind words @andrewtavis ! 
I'm really glad to hear that you appreciated my work. 
I will definitely check the new query writing guide and explore other language.
 Looking forward to collaborating more! 😊
