### ISSUE TITLE
Create Urdu adjectives extraction query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#242]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into create a directory and query in [src/scribe_data/language_data_extraction/Urdu](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Urdu) to get all the adjectives and interesting data points for Urdu. We can use code for getting adjectives from other languages, and from there we can check Urdu verbs on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain data points as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

### Contribution

Happy to support as needed and review a PR when one's ready 😊

**Comment by andrewtavis** [comment]
CC @Ekikereabasi-Nk :)

**Comment by Ekikereabasi-Nk** [comment]
Hi, @andrewtavis I will start working on it

**Comment by andrewtavis** [comment]
Fantastic, @Ekikereabasi-Nk! Bengali has an adjectives query that this can be based on 😊

**Comment by andrewtavis** [comment]
Closed by #248 🚀 Thanks so much for the hard work here, @Ekikereabasi-Nk! :)
