### ISSUE TITLE
Create Korean data process queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#243]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the `src/scribe_data/language_data_extraction/Korean` files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Korean data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

### Contribution

Happy to support as needed and review the code when it's been sent as a pull request! 😊

**Comment by Calabi8907** [comment]
Thank you for opening this issue! Although my understanding of this open-source project is still limited, I will do my best to contribute to this issue!

**Comment by andrewtavis** [comment]
Happy to open it for you, @Calabi8907! Would be great if your teammates could also write in here so I have an understanding of who all is working on this :)

**Comment by yerimmii** [comment]
I'd like to participate in this issue, too!

**Comment by andrewtavis** [comment]
Running [src/scribe_data/check_language_data.sparql](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/check_language_data.sparql) for Korean by replacing `Q9176` for the English QID, it looks like there is enough data to explore :) It's not thousands, but there are hundreds of nouns and almost 100 verbs. More data will be added later, I'm sure 😊

**Comment by hydrationn** [comment]
I'd like to participate, too!

**Comment by kyw0803** [comment]
@andrewtavis Could this issue be assigned to me?

**Comment by andrewtavis** [comment]
Checking with @Calabi8907: is everyone in this issue now part of your team? Just want to make sure. If they're not, also let me know if it's ok to assign them :)

**Comment by Calabi8907** [comment]
That's everyone on my team. no one else :)

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Let us know if any support is needed here!

**Comment by Nowshin1077** [comment]
Hi @andrewtavis, Hope you are fine. Can I add Korean "Adjectives" and "Noun" queries?

**Comment by win929** [comment]
Hello, I clicked the wrong thing, so I got to remove the assignment, can you add it again? This is my fault. Sorry.

**Comment by andrewtavis** [comment]
Alright all, we just need nouns and we can close this 😊 Would be great to get this done sooner rather than later, but take your time :)

**Comment by andrewtavis** [comment]
Checking something here :) If any of you are Korean native speakers and would have interest, it'd be great to get some support with the localization issue for the applications in https://github.com/scribe-org/Scribe-i18n/issues/53 🌐

**Comment by andrewtavis** [comment]
All done here 😊 Thanks for the great work, all!
