### ISSUE TITLE
Create Scribe-Data Swahili Adejctives process queries

### ISSUE THREAD

**Issue by VNW22** [scribe-org/Scribe-Data#254]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This is a seperate issue that I am working on related to [issue 214](https://github.com/scribe-org/Scribe-Data/issues/214) that adds adjectives to Swahili Data Process Queries

**Comment by VNW22** [comment]
@andrewtavis I have created the issue to track Swahili adjectives, please assign it to me.

**Comment by andrewtavis** [comment]
Sounds good, @VNW22! Thanks for making the issue :)

**Comment by VNW22** [comment]
@andrewtavis Are there any other issues i can work on or create?

**Comment by andrewtavis** [comment]
What other languages would you be interest in looking into, @VNW22? Thanks for your interest in making some issues! Maybe check this [this table here](https://www.wikidata.org/wiki/Wikidata:Lexicographical_data/Statistics/Counts_of_various_things_by_language) for a language that has data on Wikidata? 😊

**Comment by VNW22** [comment]
okay, l'll check it out

**Comment by andrewtavis** [comment]
Closed in #269 🚀 Let's continue the discussion in #214, @VNW22! 😊
