### ISSUE TITLE
Create English Adjective Query

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#257]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

English

### Description

This issue would look into create a directory and query in [src/scribe_data/language_data_extraction/English](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/English) to get all the adjectives and interesting data points for English. We can then expand the query with optional selections of certain data points as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

**Comment by KesharwaniArpita** [comment]
@andrewtavis I noticed that there is no query to retrieve the adjectives in English form wikidata, so I opened the issue. Can you kindly assign the hacktoberfest label to this issue?

**Comment by andrewtavis** [comment]
Thanks for making the issue, @KesharwaniArpita! :)

**Comment by andrewtavis** [comment]
Closed by #259 🚀 Thanks for the work here, @KesharwaniArpita!
