### ISSUE TITLE
`get` Method Not Saving Data in the User-Specified Output Directory

### ISSUE THREAD

**Issue by john-thuo1** [scribe-org/Scribe-Data#260]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

![Screenshot 2024-10-06 045816](https://github.com/user-attachments/assets/e9461bf1-49d1-4103-9a46-abab4878d77c)

### Issue Summary
When running the `scribe-data get` command, the user-specified output directory is created, but the downloaded data is not saved in this directory. Instead, the data is saved in the default directory defined in `src/utils.py` (`DEFAULT_JSON_EXPORT_DIR = "scribe_data_json_export"`).

### Command Executed
```bash
scribe-data get --language German --data-type nouns --output-dir ./fli -ot json

## Steps to Reproduce

1. Run the command:

    ```bash
    scribe-data get --language German --data-type nouns --output-dir ./fli -ot json
    ```

2. Check the output directory:

    - **Expected Behavior** - Data should be saved in the user-specified directory `./fli` (i.e., `./fli/German/nouns.json`).
    - **Actual Behavior** - 
        - The directory `./fli` is created as expected.
        - However, the data is saved in the default directory `scribe_data_json_export` (i.e., `scribe_data_json_export/German/nouns.json`).

---

## Environment

- **OS** -  [Windows 11 WSL 2(Ubuntu 22.04)]
- **Python version** -  [Python 3.10]
---

## Relevant Code Section

```src/scribe_data/cli/get.py

**Comment by axif0** [comment]
Working on that.

**Comment by john-thuo1** [comment]
@axif0  No problem, you can go ahead and work on it.

**Comment by SethiShreya** [comment]
@john-thuo1 I was having this issue, and I want to collaborate in this issue too.

**Comment by Ekikereabasi-Nk** [comment]
@axif0 and @john-thuo1 I have an idea how to fix it. 

- Modify query_data.py to Handle output_dir:
   Pass output_dir to query_data. Update it to accept the output_dir parameter
  def query_data(languages=None, word_types=None, overwrite=None, output_dir=None): (Output_dir =None is not in the existing query_data.py file on scribe-data)

- Save Results in output_dir: 
    Update the logic within query_data to save the results in the user-specified directory
      export_dir = Path(output_dir) / lang.capitalize() if output_dir else Path(DEFAULT_JSON_EXPORT_DIR) / lang.capitalize()
       Instead of export_dir = Path(DEFAULT_JSON_EXPORT_DIR) / lang.capitalize()
-Modify the File Path for Saving Data:
  file_path = export_dir / f"{target_type}.json"  

Just try it. (it's a suggestion)

**Comment by SethiShreya** [comment]
https://github.com/user-attachments/assets/1d68bbcb-6180-4a62-9bf4-6cd9dc01d8c8

Solved this issue, now we can user can specify any output directory and data will be saved there only.

**Comment by andrewtavis** [comment]
Working off of @SethiShreya's PR now to fix this :)

**Comment by andrewtavis** [comment]
#263 just got merged, all :) Likely not perfect, but was working for me. Let's test a bit and maybe there are some tests we could write for this.

**Comment by axif0** [comment]
Nice .. @andrewtavis in utils.py for `export_formatted_data`, `load_queried_data` the path `scribe_data_json_export` is statically defined previously. And No user defined path was passing from like format_noun.py to utils. I was thinking saving the user define path in a temp file and call that in utils.py though it is not a best approach I think. 

Can we remove [export_json](https://github.com/scribe-org/Scribe-Data/blob/02c7e1bca7c09649ca63b2b3ea3ba78fda3625f8/src/scribe_data/cli/convert.py#L38) function as it is not necessary ?

**Comment by andrewtavis** [comment]
I was thinking about `export_json` as well, @axif0. Ultimately the query process exports data and the formatting scripts can as well. This to me should be `convert_to_json`. It would be ideal if we had two new Python issues that Outreachy interns could work on:

- One that's converting `export_json` to `convert_json`, which does the opposite of the CSV/TSV and SQLite processes
- Another that's blocked by the first that's to convert from CSV/TSV to SQLite, which basically would be a combination of `convert_to_json` and one of the other functions we already have (first to JSON and then to the target type)

If someone wanted to make those issues, then by all means write in here that you'll make them and then others can work on them 😊 Or of course the person who makes the issues can also work on them.

How are we doing here though? Do we need to do any further testing? Can we check the get tests and maybe expand them? I needed to simplify them slightly last night as we had things in get that were actually for convert/

**Comment by andrewtavis** [comment]
Actually come to think of it, the first point above is covered by #213 mostly. @john-thuo1, do you want to just make sure that you also include the transition to `convert_to_json` in your work for that issue?

**Comment by andrewtavis** [comment]
And then we can make a concert between SQLite and CSV/TSV issue :)

**Comment by john-thuo1** [comment]
@andrewtavis Sure! I can work on it as well. I am trying to get the outputs in different file formats(json, csv)  as indicated in #213  but json is the only file format that is currently working with `get`.  Is this sth you have also observed?

After the changes, does it mean that `get` method will download the files as json only and then the `convert` method will handle conversion to other file formats?

**Comment by andrewtavis** [comment]
The original idea was that convert would be called in the background for get CSV/TSV or SQLite. It would be great if you could migrate the functionality to this, @john-thuo1! We can get a JSON down and check that the conversion scripts are working, and then we can integrate convert into get in cases where the user wants to get a different data type than JSON 😊

**Comment by andrewtavis** [comment]
Ok, post my changes and @axif0's in #274, how are we doing here? :)

**Comment by andrewtavis** [comment]
Let's close this out then! Thanks for all the hard work, all 😊
