### ISSUE TITLE
CLI Get functionality bug fix

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#261]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

- [X] Currently get functionality can't handle capitalization.

- [X] Remove duplicate overwrite message showing.

- [X] Need to add tests 

![image](https://github.com/user-attachments/assets/71352791-2316-49b8-9fcc-2fe39a183bff)

This should probably fix #260 path issues too. Working on that.

**Comment by andrewtavis** [comment]
Closed by #267 🚀 Thanks for all the work you've been doing recently, @axif0! You've been a great help to a successful Outreachy so far :)
