### ISSUE TITLE
Expand Italian verbs query

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#273]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In recent testing I realized that the Italian verb modeling has now been standardized. In the past - unlike other Latin languages - Italian had its forms in combined properties like `first person singular` rather than the standard of `first person` and `singular` separately. We now need to update the query to split all of the properties to their separate forms. We'll know that the query works when all the verb conjugations can be seen when running the query in the [Wikidata Query Service UI](https://query.wikidata.org/).

### Contribution

Happy to support as needed and review the PR when it's ready! 😊

**Comment by OkpePhillips** [comment]
Hi @andrewtavis, could you assign this to me?

**Comment by andrewtavis** [comment]
Thanks for picking this up, @OkpePhillips! This will be key for the next Scribe-iOS update, so really appreciate your help!

**Comment by VNW22** [comment]
hey @andrewtavis I'd also like to work on this, @OkpePhillips can we work together on this?

**Comment by andrewtavis** [comment]
There's only one query to work on here @VNW22, so maybe another issue would make more sense? Do you want to work on all the queries we normally do for [language_data_extraction/Chinese/Mandarin](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction/Chinese/Mandarin). Just moved that over for you :)

**Comment by VNW22** [comment]
Thanks for moving the query over. I’d be happy to work on all the queries for the language_data_extraction/Chinese/Mandarin folder.

**Comment by VNW22** [comment]
@andrewtavis Do I create the Issue?

**Comment by andrewtavis** [comment]
Sure you can, @VNW22 :) Just copy the way that the other issues are made 😊

**Comment by OkpePhillips** [comment]
This issue has been worked on. I made a PR @andrewtavis. Please review and let me know if the changes meet your expectations.

**Comment by andrewtavis** [comment]
Closed by #394 🚀 Thanks for the great work here, @OkpePhillips!
