### ISSUE TITLE
Expand Portuguese data queries

### ISSUE THREAD

**Issue by Pazil24** [scribe-org/Scribe-Data#275]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Portuguese](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Portuguese) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Portuguese data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

**Comment by GicharuElvis** [comment]
Hi @Pazil24 , could i work on this ?

**Comment by andrewtavis** [comment]
@Pazil24 made this for them to work on, @GicharuElvis, but maybe you could make a similar issue for another language for yourself? Check the issues and PRa to see if it's been made, but I think say Swedish adjectives should be available :)

**Comment by GicharuElvis** [comment]
Sure, let me have a look at it. Thank you :)

**Comment by Pazil24** [comment]
Thank you @andrewtavis for assigning me to this issue.

I think I didn't add all the necessary lables yet.

**Comment by andrewtavis** [comment]
Just added a list of data types that we want to include to this issue :) Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

**Comment by Pazil24** [comment]
@andrewtavis You changed it to Polish, so it's no longer Portuguese? Also the data types I am adding are the ones checked?

**Comment by andrewtavis** [comment]
Sorry @Pazil24, it's now back to Portuguese :) When I was switching the issues Polish was the one I was copying from 😊

Once a data type has been added it gets checked. So as of now we need to work on Portuguese adjectives and adverbs :)

**Comment by andrewtavis** [comment]
Checking in here, @Pazil24 :) Do you need some support?

**Comment by GicharuElvis** [comment]
Hi, @Pazil24 , thank you for proeeding with the issue. I was feeling under the weather but i am good now.  Would you need assistance?

**Comment by andrewtavis** [comment]
This issue is all done 😊 Thanks all for the great work!
