### ISSUE TITLE
Expand CLI commands to check data with QID

### ISSUE THREAD

**Issue by SethiShreya** [scribe-org/Scribe-Data#280]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue proposes the expansion of the existing CLI tool by introducing a new command:

`scribe-data check-data --qid Q1234567`

The purpose of this command is to check if the user-inputted language associated with the provided QID contains any data in wikidata, and if so, return the count of words available in that language.

**Details:**

**Command:** 
```scribe-data check-data --qid Q1234567```

**Functionality:**

  1. The command will verify if the language corresponding to the given QID exists in wikidata.
  2. If the language contains data, it will return the total count of words for that language.
  3. If no data exists for the language, an appropriate message will be displayed, indicating the absence of records.

**Comment by andrewtavis** [comment]
Assigning you here, @SethiShreya! Thanks for this :)

**Comment by andrewtavis** [comment]
Closed by f6685e8 :) Thanks for making the issue, @SethiShreya!
