### ISSUE TITLE
Generate keyword-emoji relationships in Hindi

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#281]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue aims to create a file that generates keyword-emoji relationships for a selection of Hindi words. This task involves associating relevant emojis with keywords (Hindi lexemes) based on their meaning, context, or cultural significance.

### Contribution

I would love to work and collaborate on this.

**Comment by KesharwaniArpita** [comment]
@andrewtavis ,can you assign me here to this issue?

**Comment by larrikin-coder** [comment]
assign me the issue.

**Comment by KesharwaniArpita** [comment]
Hey @larrikin-coder, do you have any specific idea for this? As there is only a single file to update?

I was thinking how about extending this issue to hindustani languages in wikidata. Their files will be similar too and we both can work. This way we might be able to build upon each other's work and learn.

**Comment by larrikin-coder** [comment]
@KesharwaniArpita Tell me how you are currently pursuing this issue. Will provide suggestions after understanding it.

**Comment by KesharwaniArpita** [comment]
Hi @larrikin-coder , I am still in discussion about this with Andrew you can checkout the pr.

**Comment by andrewtavis** [comment]
This issue was closed by #287 :) Thanks all!
