### ISSUE TITLE
Generate keyword-emoji relationships in Basque

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#282]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue aims to create a file that generates keyword-emoji relationships for a selection of Basque words. This task involves associating relevant emojis with keywords (Basque lexemes) based on their meaning, context, or cultural significance.

**Comment by KesharwaniArpita** [comment]
@andrewtavis Can you assign me this issue?

**Comment by hibaa03** [comment]
can i be assigned this?

**Comment by andrewtavis** [comment]
Hey @KesharwaniArpita 👋 Before we close this, I'm wondering if you have some suggestions for how to really simplify the emoji keywords process as much as possible 🤔 First, maybe we can get `emojis_per_keyword` as an argument when the file is called by the `get` process in a similar way that `file_path` is? From there, is there any other way we can simplify the `generate_emoji_keywords` files down that you can think of?

Let me know what you think!

**Comment by KesharwaniArpita** [comment]
Hey @andrewtavis andrew, thanks for the suggestion, I think just like your suggestion we could pass the language as a command-line argument too. That way, it becomes flexible(robust) for other languages too. Do you think if we will need to make data type more dynamic to accommodate that?

One more small change can be introducing error handling in case the emoji generation (`gen_emoji_lexicon`) fails due to missing language data. (For example, if the input is a language we may not have the data for,??)

What do you think?

**Comment by andrewtavis** [comment]
Your points are good, @KesharwaniArpita :) I'll make an issue to explore it a bit :)
