### ISSUE TITLE
Remove current Scribe-Data translations process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#292]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue would go through the project and remove the current machine learning based translation process from Scribe-Data. We'd remove the following dependencies:

- `torch`
- `pyarrow`
- `sentencepiece`
- `tabulate`
- `transformers`

All references to these dependencies should be removed. We'd also remove all `translations` directories from [src/scribe_data/language_data_extraction](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction). We'd see that this is complete when translations are no longer listed as data type options for the CLI 😊

**Comment by swarupn17** [comment]
Hey @andrewtavis I can do this task. Please can youbassign it to me.
Thanks !

**Comment by andrewtavis** [comment]
@KesharwaniArpita had expressed interest in this issue, @swarupn17 :) Let's wait for her to confirm whether she'd like to work on this, and in the meantime you can check many of the issues that have a list of data types at the top that you can write Wikidata queries for. If the data type hasn't been checked and no one has asked to work on it, then feel free to ask to work on it 😊

What I mean is the `Expand LANGUAGE data queries` issues :)

**Comment by andrewtavis** [comment]
Sure thing, @KesharwaniArpita! Let us know if you need any support :)

@swarupn17, feel free to check the `Expand LANGUAGE data queries` issues for data types that are needed. These are the unchecked boxes in the issue description. Write in the issue and we can assign it to you as well 😊

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis I went through the code to explore the occurrences of the aforementioned dependencies. Apparently only `torch` and `transformers` are being used. Next I'll remove these dependencies and see that it does not hamper the working of anything else.

**Comment by andrewtavis** [comment]
Sounds good, @KesharwaniArpita!

**Comment by andrewtavis** [comment]
Closed by #309 :) Thanks for your support here, @KesharwaniArpita!
