### ISSUE TITLE
Update languages metadata file and use of it thoughout project

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#293]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now the Scribe-Data CLI options are determined based on the [language_metadata.json](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/resources/language_metadata.json) file. To make maintenance of the package easier, it would be great if the options of the CLI were instead determined by the directory structure of [src/scribe_data/language_data_extraction](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction) so that the code doesn't need to be updated each time new queries are being added in.

Of key importance is also that the options of the CLI would allow for dialects as well, so for Norwegian we'd like to see `Norwegian - Bokmål` and `Norwegian - Nynorsk`, for example. How this will be achieved is open for discussion!

### Contribution

Happy to discuss how best to read in dialect sub directories and review the changes here when the PR is up!

**Comment by OmarAI2003** [comment]
I'm interested in this issue. 😃

**Comment by andrewtavis** [comment]
This would be a really good one for you, @OmarAI2003 😊 Let us know if you have any questions!

**Comment by andrewtavis** [comment]
In talking about this a bit, @OmarAI2003, we might not be able to do this. @SethiShreya and I were talking and as you said we need the QIDs as well so that we can do calls for the CLI based on QIDs as well. Without a central store of languages and their QIDs, maybe it can't work?

**Comment by OmarAI2003** [comment]
Maybe we could use the directory structure just for language names, but still keep `language_metadata.json` for properties like QIDs? Not sure if this would help, but happy to hear your thoughts!

**Comment by andrewtavis** [comment]
Is an interesting idea, but then say that we rely on the structure and then we don't get a QID added and then some functionality is broken 🤔

**Comment by OmarAI2003** [comment]
So is this issue will be closed , or is there anything that needs to be addressed?

**Comment by andrewtavis** [comment]
I'm thinking that for this one we can convert the functionality of the languages metadata file? I don't think we need the header key for it or the "languages" key where all the leagues are? You can remove the header and put all the language objects at the top level. You can also remove all of the keys that aren't the language name, iso and qid? Then from there we need to rework the reference of this metadata file throughout the project and fix the tests 😇

How does this sound, @OmarAI2003? :)

**Comment by OmarAI2003** [comment]
Sounds nice @andrewtavis, but I will need to engage in several discussions here and there along the way to make sure I'm on the same page.

**Comment by andrewtavis** [comment]
Sure thing, @OmarAI2003! Just start with getting the file down to just objects with languages, ISO-2s and QIDs at the base level, and then we can discuss from there. Happy to help as needed!

**Comment by catreedle** [comment]
> I'm thinking that for this one we can convert the functionality of the languages metadata file? I don't think we need the header key for it or the "languages" key where all the leagues are? You can remove the header and put all the language objects at the top level. You can also remove all of the keys that aren't the language name, iso and qid? Then from there we need to rework the reference of this metadata file throughout the project and fix the tests 😇
> 
> How does this sound, @OmarAI2003? :)

hi @andrewtavis 
with the languages header removed, what will the full language_metadata file look like?

**Comment by andrewtavis** [comment]
@OmarAI2003, can you send along a snippet of the current version of the file so we can all take a look? :)

**Comment by OmarAI2003** [comment]
This is the current version of the JSON file. I'm telling you not to worry about the sub-languages file path because there will be a `format_sublanguage_name` function in `utils.py` that will provide the name of the language relative to its directory. For example, a Norwegian sub-language like 'Bokmål', when called within the function `format_sublanguage_name(Bokmål, language_metadata)`, will return the language directory capitalized like `Norwegian/Bokmål`, and normal languages will be returned as it is but capitalized. There will also be a `list_all_languages` function for listing all queryable languages and sub-languages.
[language_metadata.json](https://github.com/user-attachments/files/17380641/language_metadata.json)

**Comment by catreedle** [comment]
> language_metadata.json

Thank you. Sounds great 😃

**Comment by andrewtavis** [comment]
Closed by #402 :) Thanks for the great work @OmarAI2003 and for the great conversation all!

**Comment by OmarAI2003** [comment]
> Closed by #402 :) Thanks for the great work @OmarAI2003 and for the great conversation all!

You're welcome! It was a great experience working on this, and I appreciate all the valuable feedback and discussions.
