### ISSUE TITLE
Add more datatypes in the metadata resource file

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#297]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

All

### Description

The issue aims to add more data to the `data_type_metadata.json` to include adjectives, adverbs, prepositions etc to the pre-existing data types for all the languages.

**Comment by andrewtavis** [comment]
Closed by #298 🚀 Thanks so much for all your efforts, @KesharwaniArpita!

**Comment by KesharwaniArpita** [comment]
Thank you
