### ISSUE TITLE
Expand Japanese data queries 

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#301]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Japanese](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Japanese) files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Japanese data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:
- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions
- [x] Emoji keywords

Have marked those that are already done or have PRs open, and we can work on the others 😊 If the data type can't work, then we can move to the others and open up specific issues later :)

### Contribution

Happy to support and review PRs for this as needed! Let us know if you'd like to work on one of the data types!

**Comment by andrewtavis** [comment]
Moved the work for Japanese over here :) What's the final decision we want to make on `ja` vs. `ja-hira`? I'm thinking that at this point we'd need to be able to do specific queries for each as language options in the same way that we're doing language sub directories now - i.e. both types of Norwegian beneath `/Norwegian`.

CC @wkyoshida, @henrikth93 and @AnishereMariam :)

**Comment by VNW22** [comment]
hey @andrewtavis I am currently working on this.

**Comment by andrewtavis** [comment]
Thanks @VNW22! Let us know if you need some support :)

**Comment by AnishereMariam** [comment]
@andrewtavis, that is a wonderful way of fixing it. I will reach out to @henrikth93 and we'll work on this ASAP.

@VNW22, which data type would you like to work on?... I'm always available on Matrix if you require any support.

**Comment by VNW22** [comment]
hey @AnishereMariam I’m currently working on adjectives. I’ll reach out on Matrix for the support—thanks for the offer!

**Comment by VNW22** [comment]
Hi @andrewtavis, 

I’m currently working on incorporating prepositions for Japanese, but I’m having trouble locating the correct lexical category to use for prepositions. Could you please guide me on how to approach this?

Thank you!

**Comment by andrewtavis** [comment]
Hey @VNW22 👋 If you bring in the most recent changes of the repo then you should see adverb queries for other languages. From there you need to change the language QID to Japanese, and then filter by `ja-hira` as is done in the other Japanese queries :) Let me know if you need more support!

**Comment by andrewtavis** [comment]
Hmmmmm, even without the language filter? Does Japanese have adverbs? Maybe just not on Wikidata right now. You're welcome to send the PR!

**Comment by VNW22** [comment]
i have managed to write the adverbs query, it is prepositions that i'm having trouble writing

**Comment by andrewtavis** [comment]
Ahhh! Maybe they use postpositions? Can you try that QID? I think you can find it in other queries :)

**Comment by VNW22** [comment]
i have tried postposition and also prepositions, still returning no matches found

**Comment by andrewtavis** [comment]
Maybe they're just not present. Check if Japanese has prepositions - which I assume it does - and then you'd be free to open a PR for it with the query that returns nothing. I just checked right now and it looks like it does :)

**Comment by VNW22** [comment]
okay, will do that

**Comment by andrewtavis** [comment]
Just emoji keywords here now :)

**Comment by VNW22** [comment]
Oh sorry, I'll work on the emoji keywords.

**Comment by andrewtavis** [comment]
No stress, @VNW22! Looking forward :)

**Comment by andrewtavis** [comment]
All done here! Thank you, @VNW22! 😊
