### ISSUE TITLE
Format export keys for JSON and SQLite

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#312]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now Scribe-Data export JSON keys and SQLite columns that are camelCase. Ideally these would all be snake_case as this is a bit more in line with expectations for JSON and database column formatting - snake_case works for both, and we should choose one.

We should wait on this issue so that the convert functionality isn't effected by it.

- Blocked by #213

### Contribution

CC @OmarAI2003 who had interest in this :) Happy to review and assist as needed!

**Comment by andrewtavis** [comment]
Feel free to write in here and I'll assign, @OmarAI2003 :)

**Comment by OmarAI2003** [comment]
> Feel free to write in here and I'll assign, @OmarAI2003 :)

Fine Andrew I'll investigate this tomorrow

**Comment by OmarAI2003** [comment]
So this issue is no longer blocked, right?

**Comment by andrewtavis** [comment]
Is not blocked, no

**Comment by OmarAI2003** [comment]
@andrewtavis Should I change the tsv and csv columns headers too?

**Comment by andrewtavis** [comment]
Ideally yes :)

**Comment by andrewtavis** [comment]
Thanks, @OmarAI2003! 😊

**Comment by OmarAI2003** [comment]
> Ideally yes :)

Done. But sadly some tests failed.

**Comment by andrewtavis** [comment]
Let me know if you need me to take a look :)

**Comment by OmarAI2003** [comment]
Alright. I will.

**Comment by OmarAI2003** [comment]
@andrewtavis Everything is fixed now! 🥳

**Comment by andrewtavis** [comment]
Closed by #486 😊 Appreciate all the hard work and the discussion of the solution to get to this point, @OmarAI2003!
