### ISSUE TITLE
Expanding German Language query for prepositions

### ISSUE THREAD

**Issue by Khushalsarode** [scribe-org/Scribe-Data#315]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

German Language: Q188

### Description

Cross check through out no other mention issue has been assign to this language for querying prepositions  lists.
I will query them against the  preposition entity sets available on wikidata to get related German entity to expand data on language. 
will try to select most relevant by implementing filter to language.
preposition entity: Q4833830

@andrewtavis

**Comment by andrewtavis** [comment]
Hey @Khushalsarode 👋 German emoji keywords and prepositions haven't been mentioned in issues, yes, but they have been implemented as seen in the package itself. German being the first Scribe keyboard, these data types were created as soon as they were needed for Scribe-iOS.

I'll close this as I think it makes more sense that we look into some of the other issues that still have lots of data types missing. See:

- #235
- $234
- #231

**Comment by Khushalsarode** [comment]
> Hey @Khushalsarode 👋 German emoji keywords and prepositions haven't been mentioned in issues, yes, but they have been implemented as seen in the package itself. German being the first Scribe keyboard, these data types were created as soon as they were needed for Scribe-iOS.
> 
> I'll close this as I think it makes more sense that we look into some of the other issues that still have lots of data types missing. See:
> 
> * [Expand Tajik data queries #235](https://github.com/scribe-org/Scribe-Data/issues/235)
> * [Expand Slovak data queries #234](https://github.com/scribe-org/Scribe-Data/issues/234)
> * [Expand Malayalam data queries #231](https://github.com/scribe-org/Scribe-Data/issues/231)

Oh make sense! So what shall we work on next? Any ideas ?

**Comment by andrewtavis** [comment]
Check any of those issues there and write in there to request working on a data type :)
