### ISSUE TITLE
Inconsistent PyICU behavior

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Data#33]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

[PyICU](https://pypi.org/project/PyICU/) appears to show inconsistent behavior - not confirmed, though likely due to differences from installation needs when in differing OS/environments.

Initially observed [here](https://github.com/scribe-org/Scribe-Data/pull/31#issuecomment-1505827377)

This bug issue is to continue investigation on the PyICU behavior, what causes the inconsistency, if any resolution, and if needed, what alternatives to PyICU could be used for ICU/CLDR data.

**Comment by andrewtavis** [comment]
Thank you, @wkyoshida! 🙏

**Comment by andrewtavis** [comment]
Would it make sense to maybe create a script that does the PyICU install for folks?

**Comment by andrewtavis** [comment]
Hey @wkyoshida 👋 Do you think we can get the [pyicu installation commands](https://gitlab.pyicu.org/main/pyicu#installing-pyicu) to be ran as a part of the installation build for Scribe-Data? For dockerized deployment almost certainly as we'll have more control, but also have it be something that's triggered on a pip install before the requirements file is installed? We could maybe have including PyICU be something that's an installation flag so we're not running random commands without people explicitly saying so?

**Comment by andrewtavis** [comment]
Note that #196 should make a lot of progress on this. Once that issue is done, we should check back on this and try to do whatever is needed to finalize it :)

**Comment by andrewtavis** [comment]
I'm going to close this as it's been removed as a dependency. The user has to install it themselves via their docs to use the emoji functionality :) See #196.
