### ISSUE TITLE
Expand Danish Data Queries

### ISSUE THREAD

**Issue by Kehindeadebisi** [scribe-org/Scribe-Data#342]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Danish Queries

### Description

Description
This issue would look into expanding the [src/scribe_data/language_data_extraction/Danish](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/language_data_extraction/Danish) files with as much data as are possible from the current data on Wikidata. 

### Data types to include:
- [x] Adverbs
- [x] Adjectives
- [x] Emoji keywords

**Comment by Kehindeadebisi** [comment]
@andrewtavis could you please assign this issue to me?

**Comment by andrewtavis** [comment]
Thanks for making the issue and picking it up, @Kehindeadebisi!

**Comment by Otom-obhazi** [comment]
can i be assigned this ??

**Comment by andrewtavis** [comment]
@Kehindeadebisi, are you working on all of the above, or is there something that @Otom-obhazi can also contribute to :)

**Comment by andrewtavis** [comment]
In the meantime, @Otom-obhazi, maybe check out https://github.com/scribe-org/Scribe-Data/issues/234 :) I'd be happy to assign you there :)

**Comment by Kehindeadebisi** [comment]
> @Kehindeadebisi, are you working on all of the above, or is there something that @Otom-obhazi can also contribute to? :)

oh sorry already worked on [this](https://github.com/scribe-org/Scribe-Data/pull/349), though the adjectives can be expanded @Otom-obhazi can work on that if he hasn't gotten an issue yet, however when I tried expanding it to include other available forms I noticed the query timed out so maybe he can split them right? @andrewtavis

**Comment by andrewtavis** [comment]
Yes the adjectives query should then be split like how it's done in other queries like in the [Latin queries](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction/Latin/adjectives). So @Otom-obhazi feel free to take a look at an adjectives query and @Kehindeadebisi and I can support as needed :)

**Comment by Kehindeadebisi** [comment]
Hi @Otom-obhazi is this something you will like to work on? happy to help if needed

**Comment by andrewtavis** [comment]
Closed by #349 😊 Thanks so much, @Kehindeadebisi!
