### ISSUE TITLE
Allow for lists of arguments to be validated by the CLI validation functionality

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#358]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The function `validate_language_and_data_type` was recently added to the CLI utils [here](https://github.com/scribe-org/Scribe-Data/blob/7882f8e07d96b4d93ea0f06fd722fc109588e46f/src/scribe_data/cli/cli_utils.py#L158). One thing that it does is it skips lists of arguments as it's not set up to check them now. It'd be great if we could change that such that lists passed to CLI arguments like `--language` and `--data-type` could also be validated.

With this we'd also need testing:
- Testing to make sure that this list functionality works
- Testing of the ability to pass QIDs to the `validate_language_and_data_type` function

### Contribution

Happy to support here and review a PR when one's open 😊

**Comment by axif0** [comment]
want to work on that.. @andrewtavis

**Comment by andrewtavis** [comment]
Sure thing, @axif0 :) After this, it would be good to get your help finalizing some of the queries as this is a part of the project you haven't had much experience with yet 😊

**Comment by andrewtavis** [comment]
Closed by #375 :) We can do minor issues for any further functionality that's needed, @axif0! Thanks for this 😊
