### ISSUE TITLE
Expand Chinese/Mandarin Queries

### ISSUE THREAD

**Issue by VNW22** [scribe-org/Scribe-Data#367]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the [src/scribe_data/language_data_extraction/Chinese/Mandarin](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/language_data_extraction/Chinese/Mandarin) files with as much data as are possible from the current data on Wikidata. 

Data types to include:

 - [x] Nouns
 - [x] Verbs
 - [x] Adjectives
 - [x] Adverbs
 - [x] Prepositions
 - [x] Emoji keywords

### Contribution

Currently working on this issue :)

**Comment by andrewtavis** [comment]
Note that I updated the list as @Otom-obhazi has sent along a query for adverbs, @VNW22 :)

**Comment by andrewtavis** [comment]
Closed by #370 :) Thanks much, @VNW22! Maybe you want to check some of the other issues for missing data types?
