### ISSUE TITLE
Add unit-testing and continuous-integration

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Data#37]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is for adding unit-testing and continuous-integration to the Scribe-Data project. 

Initial ideas are to use: 
- [pytest](https://pytest.org/) as the testing framework
- [GitHub Actions](https://docs.github.com/en/actions) as the platform for CI

**Note:** This issue in Scribe-Data is related to the issue https://github.com/scribe-org/Scribe-iOS/issues/8 in Scribe-iOS.

---

**Definition of Done** here can be, at minimum:
- Testing framework is setup
- CI is setup
- Some functioning tests are added

Can discuss what % coverage we would like to achieve before comfortable to close issue.

**Comment by andrewtavis** [comment]
Thanks for making this, @wkyoshida! 😊
