### ISSUE TITLE
Refactor Query Structure for Atomic SPARQL Queries

### ISSUE THREAD

**Issue by DeleMike** [scribe-org/Scribe-Data#380]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description
We are currently experiencing inconsistencies in the validation and structure of our SPARQL queries, where multiple data types (e.g., prepositions, postpositions, nouns, etc.) are combined into single queries using the VALUES keyword. This approach complicates the validation and processing of specific lexical categories and makes it harder to maintain the code.

### Expected Outcome
Refactor the existing queries to be atomic by splitting each query into its dedicated file based on a specific lexical category (e.g., `query_preposition.sparql`, `query_postposition.sparql`, `query_noun.sparql`). This change will streamline the validation process, improve maintainability, and ensure that the `wikibase:lexicalCategory wd:Q\d+` pattern can be consistently applied across all queries. Additionally, this will allow users to retrieve specific lexical categories easily, such as getting proper nouns or prepositions without extraneous data.

### Contribution
Happy to support and answer questions as needed!

**Comment by DeleMike** [comment]
@andrewtavis this is the issue.

**Comment by catreedle** [comment]
hi @DeleMike,
I would like to help with this issue if needed. 😊

**Comment by DeleMike** [comment]
okay @catreedle thanks so much for reaching out. 
I'm currently working on a fix. I will update you if there's a need 😊
