### ISSUE TITLE
Create documentation for how to write Scribe-Data queries

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#395]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue would add a new markdown file `SPARQL_QUERY_WRITING.md` to the project in the [src/scribe_data/wikidata](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/wikidata) directory that would detail how to find forms for Wikidata lexemes and outline the best practices for how to Wikidata queries for use in Scribe-Data. The general part of it can be from [a message I wrote on Matrix](https://matrix.to/#/!PeilAyAGHTRpDJmvbc:matrix.org/$cFznZh5S--I_OCHObt2mC4tlAHnT-XoJh5vCvvBRUnU?via=matrix.org), with further ideas coming from the community :)

**Comment by andrewtavis** [comment]
CC @OkpePhillips 👋

**Comment by andrewtavis** [comment]
Can you write in here so I can assign :) Others can also be assigned here, as we'll need reviewers for the file :)

**Comment by OkpePhillips** [comment]
Kindly assign it to me. Thank you

**Comment by Aeeshah1** [comment]
Can I help with this as well?

**Comment by KesharwaniArpita** [comment]
@andrewtavis Can i help here too?

**Comment by andrewtavis** [comment]
Sure! Let's let @OkpePhillips do the PR, but you both can help review :)

**Comment by andrewtavis** [comment]
Thanks @OkpePhillips and all for the great work here! This will be sooo useful for the community :)
