### ISSUE TITLE
Create Igbo data process queries

### ISSUE THREAD

**Issue by Ekikereabasi-Nk** [scribe-org/Scribe-Data#399]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue aims to expand to expand the `src/scribe_data/language_data_extraction/Igbo` files with as much data as possible from the current data on Wikidata. We can utilize existing code from other language implementations to examine available Igbo linguistic data on Wikidata, particularly focusing on verb conjugations, noun classes, and tonal patterns specific to Igbo. The SPARQL queries will be expanded with optional selections of various forms as implemented in other language queries, ensuring comprehensive coverage of Igbo's linguistic features.

## Data Types to Extract
- [x] **Nouns**
- [x] **Verbs** 
- [x] **Adjectives**
- [x] **Adverbs**
- [x] **Prepositions**

### Contribution

Happy to work and collaborate with others on this feature :mag:!

**Comment by Ebeleokolo** [comment]
Hello @andrewtavis I would like to join on this task. @Ekikereabasi-Nk are you already working on some feature? please let me know what part you're already working on so i will know which to take. thank you

**Comment by Otom-obhazi** [comment]
i will like to be assigned to this @andrewtavis

**Comment by Ekikereabasi-Nk** [comment]
Hi, @Otom-obhazi I'm already working on it. But if you are still interested you can work on the verbs

**Comment by Otom-obhazi** [comment]
@andrewtavis @Ekikereabasi-Nk  there is not much information on grammar feature

**Comment by Ekikereabasi-Nk** [comment]
Yes @Otom-obhazi just write the query to retrieve all verbs. Thank you

**Comment by Ekikereabasi-Nk** [comment]
@Otom-obhazi please check again, there are grammatical feature for verb. The one I have seen include "'verb' 'present tense' 'present participle' 'past tense' 'noun'
 'third person present' 'present continuous' 'plural' 'synonym'
 'past participle' 'infinitive' 'adjective' 'singular' 'suffix'
 'imperative' 'affix' 'prefix' 'auxiliary verb' 'perfective verb'
 'negation' 'intransitive verb' 'nominalized verb' 'word stem'
 'participle' 'nominal' 'normative reference' 'slang' 'past perfect'
 'action' 'future tense' 'phrasal verb' 'gerund' 'adverbial suffix'
 'infinitive marker' 'transitive verb' 'opposite' 'phrase'"

**Comment by Otom-obhazi** [comment]
okay

**Comment by GicharuElvis** [comment]
Hi @Ekikereabasi-Nk , i'd also like to help @Otom-obhazi contribute.

**Comment by Ekikereabasi-Nk** [comment]
Hi, @GicharuElvis, thanks for your interest, but all the data queries have been done

**Comment by andrewtavis** [comment]
Yes we're all finished here 🚀 Thanks @Ekikereabasi-Nk and @Otom-obhazi!

**Comment by Otom-obhazi** [comment]
https://github.com/scribe-org/Scribe-Data/pull/422
made the correction, let me know if it's okay?

and please can i be assigned to another issue if its good.
