### ISSUE TITLE
Create Persian data process queries

### ISSUE THREAD

**Issue by catreedle** [scribe-org/Scribe-Data#400]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Persian

### Description

This issue would look into expanding the src/scribe_data/language_data_extraction/Persian files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Persian data on Wikidata for what conjugations are available. We would likely need to filter for fa for Farsi. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:

- [x] Nouns
- [x]  Verbs
- [x]  Adjectives
- [x]  Adverbs
- [x]  Prepositions

**Contribution**
Happy to work on this and help anyone interested 😊

**Comment by VNW22** [comment]
hey @catreedle can I work with you on this?

**Comment by catreedle** [comment]
hey @VNW22, sure can! :)
I have not started any work on this. We can comment here to keep track of which data type we're working on? What do you think?

**Comment by andrewtavis** [comment]
Keep in mind that we'll need a language filter for Farsi via "fa" as is done in the Hindustani queries :) Not 100% sure, but worth checking.

**Comment by VNW22** [comment]
> hey @VNW22, sure can! :) I have not started any work on this. We can comment here to keep track of which data type we're working on? What do you think?

I can do verbs and prepositions

**Comment by catreedle** [comment]
> Keep in mind that we'll need a language filter for Farsi via "fa" as is done in the Hindustani queries :) Not 100% sure, but worth checking.

hi @andrewtavis, how to decide/check if a language needs a filter?

**Comment by andrewtavis** [comment]
Check to see if the forms have more than one language on them :) So you can see for say a Hindustani lexeme that all the forms have hi and ur equivalents. If there's nothing like that for Persian, then maybe we don't have to worry 😊

**Comment by catreedle** [comment]
I'll work on adverbs :) @VNW22
