### ISSUE TITLE
Create Dagbani data process queries

### ISSUE THREAD

**Issue by Ebeleokolo** [scribe-org/Scribe-Data#401]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue aims to expand the src/scribe_data/language_data_extraction/Dagbani files with as much data as possible from the current data on Wikidata. We can utilize existing code from other language implementations to examine available Dagbani linguistic data on Wikidata, particularly focusing on verb conjugations, noun classes, and tonal patterns specific to Dagbani. The SPARQL queries will be expanded with optional selections of various forms as implemented in other language queries, ensuring comprehensive coverage of Dagbani's linguistic [features.]

    **### Data Types to Extract**

- [x] Nouns
- [x] Verbs
- [x] Adjectives
- [x] Adverbs
- [x] Prepositions

### Contribution

I am happy to work and collaborate with others on this feature 🔍!

**Comment by VNW22** [comment]
hey @Ebeleokolo can I work with you on this?

**Comment by Ebeleokolo** [comment]
Hey @VNW22, Yes. I am working on the first 3 (Noun, Verbs and Adjective)

**Comment by andrewtavis** [comment]
Do you want to take care of @VNW22 adverbs and prepositions then?

**Comment by andrewtavis** [comment]
Should be easy enough for you 😊

**Comment by VNW22** [comment]
yeah I'll work on the adverbs and prepositions

**Comment by Nowshin1077** [comment]
Hi @VNW22 @Ebeleokolo, I adding the noun query. I hope you guys will not mind 😊

**Comment by VNW22** [comment]
Hi @Nowshin1077 , I don’t mind at all! 😊 Thanks for the update.
