### ISSUE TITLE
Create data queries for Northern Sami

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#405]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Northern Sami

### Description

This issue would look into creating and expanding the `src/scribe_data/language_data_extraction/Northern Sami` files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Northern Sami **(QID: Q33947)** data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:

 Nouns
 Verbs
 Adjectives
 Adverbs
 Prepositions
 
### Contribution
Happy to work on this and help anyone interested 😊

**Comment by KesharwaniArpita** [comment]
@andrewtavis can you assign me?

**Comment by andrewtavis** [comment]
Can we finalize Latin verbs before moving on to this one, @KesharwaniArpita? :)

**Comment by KesharwaniArpita** [comment]
Yeah, sure.

**Comment by VNW22** [comment]
hey @KesharwaniArpita can I work with you on this queries?

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis can you assign us?

**Comment by andrewtavis** [comment]
Closed by 9329960 :) Thank for the work here, both of you!
