### ISSUE TITLE
Expand LATIN verb queries

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#411]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Latin

### Description

This issue would look into expanding the `src/scribe_data/language_data_extraction/Latin/verbs` files with as much data as possible from the current data on Wikidata. We can use code to get data from other languages, and from there we can check Latin data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

**Comment by KesharwaniArpita** [comment]
Hi @andrewtavis I have started working on Latin verbs but the verbs seem to be too interconnected resulting in redundant data in large amount? Is there any other way we can try arranging the forms to reduce the redundancy? Currently I am trying to extract the forms of verbs in the terms of tenses.

**Comment by andrewtavis** [comment]
Big thing here @KesharwaniArpita is that we need to include all of the properties so that the forms have a unique identifier. Beyond that, if you have some forms that maybe have the same set of properties, but one has an extra one, then you can use `FILTER NOT EXISTS` as is done in other queries to say that the other form is not included.

**Comment by Otom-obhazi** [comment]
@andrewtavis can i help @KesharwaniArpita with this??

**Comment by andrewtavis** [comment]
Closing this as #444 is a repeat issue and there's more activity there :)
