### ISSUE TITLE
Create Latvian data process queries

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#413]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue would look into expanding the src/scribe_data/language_data_extraction/Latvian files with as much data as are possible from the current data on Wikidata. We can use code for getting data from other languages, and from there we can check Latvian data on Wikidata for what conjugations are available. We can then expand the query with optional selections of certain forms as is done in other SPARQL queries. The query can be tried on the [Wikidata Query Service UI](https://query.wikidata.org/) during development :)

Data types to include:

- [x]  Nouns
- [x]  Verbs
- [x]  Adjectives
- [x]  Adverbs
- [x]  Prepositions

### Contribution

 
After finishing the issue on Latin data queries adverbs and the prepositions, I would like to work here

**Comment by Khushalsarode** [comment]
@axif0 are you working on this?

**Comment by axif0** [comment]
@Khushalsarode  ya..  If you want maybe we can split the data-types for latvian.

**Comment by andrewtavis** [comment]
Looks like we're all done here. Thanks both of you! :)
