### ISSUE TITLE
Add GitHub Action to Check for Dead Links in Documentation

### ISSUE THREAD

**Issue by mhmohona** [scribe-org/Scribe-Data#419]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

We need a GitHub Action that automatically checks for dead links in Sphinx-generated documentation when changes are submitted (e.g., pull requests or pushes). This will ensure all links remain valid.

### Contribution

Happy to support with answers to questions and reviewing a PR eventually 😊

**Comment by Khushalsarode** [comment]
shall I work on this?

**Comment by mhmohona** [comment]
Please go ahead @Khushalsarode!

**Comment by Khushalsarode** [comment]
Created an python script that easy list the only broken link in formated manner 
Like file location, link,  broken status 
Script includes regex to get only urls and can pass multiple file as parameters. 
@andrewtavis 
I will attach screen shots for preview.

**Comment by andrewtavis** [comment]
Sounds interesting, @Khushalsarode :) Did you forget to attach the screenshot? Do you want to open a PR?

**Comment by Khushalsarode** [comment]
![Screenshot 2024-11-17 032635](https://github.com/user-attachments/assets/79676677-78e6-4a47-897a-de1f47cd5a1a)
![Screenshot 2024-11-17 032614](https://github.com/user-attachments/assets/72ee00c3-e5d1-4029-9a26-f0519ea3d44a)

need to pass file/folder as list of path ',' separated.

**Comment by andrewtavis** [comment]
Can you open a PR with the code, @Khushalsarode?

**Comment by Khushalsarode** [comment]
@andrewtavis 
further we can add this to workflow for checks!
we can make it cli based to check link by passing file or list of file as parameter to check?

**Comment by andrewtavis** [comment]
Closing this as we have pre-commit to check the markdown links. All of these thinks are the same as those that are in the docs, so we'll just need to change them in parallel. Beyond this, we also have linting for Sphinx added in via e5cb5dd :)

Thanks all for the efforts here!
