### ISSUE TITLE
language_metadata.json qid error handling

### ISSUE THREAD

**Issue by catreedle** [scribe-org/Scribe-Data#423]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue Description:

While working on a function to validate language properties, I encountered an error after deleting the `qid` from `language_metadata.json`. This error originates from `cli_utils.py`.

### Steps to Reproduce:

1. Open `language_metadata.json`.
2. Delete the qid key from any language or sub-language entry.
3. Run a CLI command that uses `cli_utils.py`, such as `scribe-data t -l french`.
4. Observe the error thrown due to the missing qid.

![qid](https://github.com/user-attachments/assets/ef122ff0-83cf-4670-9e41-5891ef552446)

### Expected Behavior:

The code should handle missing qid values gracefully without throwing an error. It should either:

1. Log a warning or message indicating the missing qid, or
2. Safely skip over languages/sub-languages without qid, without causing the program to crash.

### Proposed Fix:

In `cli_utils.py`, replace instances of `lang_data["qid"]` and `sub_lang_data["qid"]` with `lang_data.get("qid")` and `sub_lang_data.get("qid")` respectively. This will prevent errors when the qid key is missing.

**Comment by Collins-Webdev** [comment]
Hello @catreedle , @andrewtavis  👋🏼
I'm ready to work on this bug. Can you please assign me to this task?

**Comment by catreedle** [comment]
sure, @Collins-Webdev 😊

**Comment by Collins-Webdev** [comment]
> sure, @Collins-Webdev 😊

Thanks @catreedle, I'll get on it and let you know if anything comes up 😊. But it looks like I still haven't been assigned to it though🤔.

**Comment by catreedle** [comment]
> > sure, @Collins-Webdev 😊
> 
> Thanks @catreedle, I'll get on it and let you know if anything comes up 😊. But it looks like I still haven't been assigned to it though🤔.

I can't assign people. We'll need to wait for @andrewtavis for that 😊

**Comment by Collins-Webdev** [comment]
> > > sure, @Collins-Webdev 😊
> > 
> > 
> > Thanks @catreedle, I'll get on it and let you know if anything comes up 😊. But it looks like I still haven't been assigned to it though🤔.
> 
> I can't assign people. We'll need to wait for @andrewtavis for that 😊

Got it 👍🏽

**Comment by andrewtavis** [comment]
Assigned :) Let us know if you need some support, @Collins-Webdev!

**Comment by Collins-Webdev** [comment]
> Assigned :) Let us know if you need some support, @Collins-Webdev!

Sure @andrewtavis 😊, thanks for assigning me the project 🙏🏽

**Comment by Collins-Webdev** [comment]
Hello there👋🏼,
I made the PR here : https://github.com/scribe-org/Scribe-Data/pull/428/, please review it and let me know if there is anything you want me to improve 😊.

**Comment by andrewtavis** [comment]
Closed by #428. Thanks, @Collins-Webdev, and thanks for the issue @catreedle!
