### ISSUE TITLE
Move `language_data_extraction` under `/wikidata` and lower case all languages

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#446]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In the most recent dev sync we decided that the structure of Scribe-Data would determine functionality of only Wikidata based processes. Because of this, all the queries and functionality within `language_data_extraction` should move under the `/src/scribe_data/wikidata` directory as emoji, translation and synonym functionality will all be centralized. This would make it more clear that all of these language files are for Wikidata functionality alone.

Along with this, the all language directories should be lower cased and calls to `.lower()` and `capitalize()` within language processes should be removed except for in print statements. Language args should be lower cased on first parse, and only when languages are displayed to the user should they be capitalized.

### Contribution

Happy to discuss this and review once the work is done 😊

**Comment by Ekikereabasi-Nk** [comment]
Hi @andrewtavis I will love to be assign to this. @KesharwaniArpita @catreedle will you be interested in working on the issue, we so shared ideas.

**Comment by Khushalsarode** [comment]
@andrewtavis I would like to work on this!

**Comment by KesharwaniArpita** [comment]
Sure!!! @Ekikereabasi-Nk . I am more than happy to work together!!!

**Comment by catreedle** [comment]
> Hi @andrewtavis I will love to be assign to this. @KesharwaniArpita @catreedle will you be interested in working on this issue, we can share ideas.

sure :)

**Comment by SethiShreya** [comment]
I would like to work on this too:)

**Comment by SethiShreya** [comment]
Btw @Ekikereabasi-Nk and @KesharwaniArpita how is the work for centralised emoji going? Is it done now?

**Comment by Ekikereabasi-Nk** [comment]
@SethiShreya check on #379 I have updated the centralized logic. @KesharwaniArpita Please are you done with deleting the `generate_emoji_keyword` from each language folder

**Comment by KesharwaniArpita** [comment]
Hi @SethiShreya and @Ekikereabasi-Nk I have completely deleted the emoji keyword folders for all the languages and raised the PR too.

**Comment by Ekikereabasi-Nk** [comment]
@KesharwaniArpita Thank you.

**Comment by SethiShreya** [comment]
And @Ekikereabasi-Nk what about you?

**Comment by Ekikereabasi-Nk** [comment]
@SethiShreya I done with mine on Centralizing the emoji keyword generation logic #379

**Comment by SethiShreya** [comment]
Great @Ekikereabasi-Nk

**Comment by andrewtavis** [comment]
Thanks all for the collaboration here :) I'll get back to the PRs a bit later today 😊

**Comment by catreedle** [comment]
hi @andrewtavis, to clarify, do we move language_data_extraction and its contents under wikidata, or do we move the contents of language_data_extraction and delete language_data_extraction?

**Comment by andrewtavis** [comment]
Thanks for asking for clarification, @catreedle :) We're moving `language_data_extraction` and its contents under `/wikidata`. So we still want all of the language directories in their own folder, but it should be moved to indicate that these files are only use for Wikidata processes 😊

**Comment by SethiShreya** [comment]
@catreedle @KesharwaniArpita @Ekikereabasi-Nk happy to collaborate with you, according to me we have all these works
- Moving of all the files to  /src/scribe_data/wikidata
- Fix in cli_utils.py, convert.py, list.py,  total.py, query_data.py, utils.py, check_query_identifiers.py
- lower once in main.py
- Also we need to change directory path too in all these files.

@andrewtavis this is what we are supposed to do, right?

**Comment by andrewtavis** [comment]
Yes exactly, @SethiShreya :) Thanks for explaining it so concisely :)

**Comment by SethiShreya** [comment]
Okay, then let us all choose one and collaborate :)

**Comment by catreedle** [comment]
> Okay, then let us all choose one and collaborate :)

Thank you for detailing the task, @SethiShreya. I'll do the 1st one

**Comment by catreedle** [comment]
We also don't need all the `emoji_keywords` directory, right?

**Comment by Ekikereabasi-Nk** [comment]
> Okay, then let us all choose one and collaborate :)

> I will be pick the last one

**Comment by SethiShreya** [comment]
I will do the 2nd, so @KesharwaniArpita you can do 3rd one, is that fine with you?

**Comment by catreedle** [comment]
opened a PR https://github.com/scribe-org/Scribe-Data/pull/454 please review and let me know if something amiss :)

**Comment by catreedle** [comment]
Hi @andrewtavis and everyone, some language directories have an empty `__init__.py` file in them. What's the purpose of this?

**Comment by andrewtavis** [comment]
Likely a mistake. The emoji ones will be removed, but the bare language directories do need one :)

**Comment by andrewtavis** [comment]
Base* :) So like English and all of the sub directories.

**Comment by andrewtavis** [comment]
They might not need them after all, but the thing is that if we eventually do Python formatting, then they will need them as `__init__.py` is kind of the way that Python packages know which files are where in the structure.

**Comment by catreedle** [comment]
> They might not need them after all, but the thing is that if we eventually do Python formatting, then they will need them as `__init__.py` is kind of the way that Python packages know which files are where in the structure.

Ok @andrewtavis. Then I'll leave them as is. Thank you :)

**Comment by KesharwaniArpita** [comment]
> I will do the 2nd, so @KesharwaniArpita you can do 3rd one, is that fine with you?

Sure @SethiShreya .Thanks for the explanation! Just saw the msg(was a bit busy with research stuff)

**Comment by andrewtavis** [comment]
I think this one's closed via #460 and #454 :) Thanks all for the collaboration and hard work!
