### ISSUE TITLE
Create workflow to check query forms

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#450]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to document work that I've been doing to create a check for form identifiers within all Scribe-Data queries. The check goes through and derives the properties of all forms and create a new metadata file for lexeme forms from which a naming criteria is derived.

### Contribution

I'm working on this. Current status at time of writing is that I need to add in a check for whether all forms are actually returned in the query, that each returned form is unique, and that returned forms are ordered in the same way as the metadata file. From there also a minor check to see that the query docstring is correct would be good.

From there I need to go through and rename all the forms in the queries that have issues :)

**Comment by DeleMike** [comment]
Hello @andrewtavis 👋🏾, well done for #450 !! 
I'm happy to assist you on this issue. Is there any task I can help with?

**Comment by andrewtavis** [comment]
Thanks for your offer to help, @DeleMike :) Maybe I can solve the current issues with the queries later tonight, and from there we can make some issues for the extra features?

**Comment by DeleMike** [comment]
Sure! I will ping you later, then!

**Comment by andrewtavis** [comment]
Ok @DeleMike, with #451 in we now need the following:

- [] Add in a check for whether all forms are actually returned in the query (i.e. are there optional selections that are not brought up to the select statement)
- [] Add a check that each returned form is unique (never ?plural ?plural)
- [] Add a check that the returned forms are ordered in the same way as the metadata file and that their optional statements match (this is a simple as checking the top against the labels for the generated form labels)
- [] General testing and error handling

CC @axif0 who's also looking for Python work to do :) Do you all want to plan out the work here?

**Comment by DeleMike** [comment]
Thanks @andrewtavis! 

We will look into it. @axif0 how about we break this into parts? 

---
**Some questions:**
For these checks, how do we wanna verify outputs? Are we gonna make network calls for all the checks? 

Also, I believe these checks will be part of our local tests, yes?

**Comment by andrewtavis** [comment]
Honestly let's keep this to expanding the `lexeme_form_metadata.json` file. Yes it's more work for us, but doing network calls for all of this each time a PR commit is made would be way to much usage of a common database :) 

And ya we really should do a single Python or shell script that runs all of the checks we've been working on locally and add a note on that into the testing section of the contriving guide 😊

**Comment by axif0** [comment]
I'll look forward `Add a check that each returned form is unique (never ?plural ?plural)` and ..

**Comment by andrewtavis** [comment]
This would be great, @axif0! This can form the basis of some of the other work here. So as with getting all the form texts, we should also parse and get all forms that are being returned from the query. This first check will be to make sure that each is unique, and from there we can work towards making sure that what's being returned matches what's in the forms 😊

**Comment by axif0** [comment]
@andrewtavis if a form is defined in an OPTIONAL block within our SPARQL query but is not included in the SELECT statement. then what should we do?  

like [here](https://github.com/scribe-org/Scribe-Data/blob/399efe2cca42b038e709d38c17530c0d063193aa/src/scribe_data/language_data_extraction/Czech/nouns/query_nouns.sparql#L34) 

should I add `nounGender` in select statement or remove the optional block?
![image](https://github.com/user-attachments/assets/b26b4ccc-1fd7-4809-95ed-5a9653be75f5)

**Comment by DeleMike** [comment]
**[OFF TOPIC]**
Hey everyone, I'm currently not strong enough. I fell ill. 

But hoping to come back soon and resolve this issue! They said I need rest.

**Comment by andrewtavis** [comment]
No stress, @DeleMike! Please take care and feel better soon!

**Comment by OmarAI2003** [comment]
> **[OFF TOPIC]** Hey everyone, I'm currently not strong enough. I fell ill.
> 
> But hoping to come back soon and resolve this issue! They said I need rest.
> 
> EDIT: I had to drop this update so that it doesn't seem I am silent.

Thank you for the update. 

I hope you feel better soon! If there’s anything I can do to assist with this issue while you’re away, please let me know, and I’m happy to coordinate with @andrewtavis and @axif0 if needed.

Take care!

**Comment by andrewtavis** [comment]
Ok @axif0 finished the first two :) @OmarAI2003, do you want to do the edit to this process that checks to make sure that the order of the returned forms is the same as how they appear below in the query? And @KesharwaniArpita, can you check the functions and make sure that they have the needed checks included?

**Comment by KesharwaniArpita** [comment]
Sure @andrewtavis

**Comment by OmarAI2003** [comment]
Sure, thanks, Andrew.

**Comment by andrewtavis** [comment]
Would be the functions in `check_query_forms.py`, @KesharwaniArpita :)

**Comment by DeleMike** [comment]
Thank you so much everyone! ✨
This means a lot!

**Comment by andrewtavis** [comment]
Great to hear, @DeleMike!

**Comment by andrewtavis** [comment]
So last thing here is to check that the actual QIDs that make up the form after `wikibase:grammaticalFeature` are in order, right? :) Thanks all so much for the amazing work here!

**Comment by OmarAI2003** [comment]
> So last thing here is to check that the actual QIDs that make up the form after `wikibase:grammaticalFeature` are in order, right? :) Thanks all so much for the amazing work here!

Yeah, and the ordering of the labels in sELECT to be based on the lexeme forms JSON.

**Comment by KesharwaniArpita** [comment]
Yess!!

**Comment by andrewtavis** [comment]
@OmarAI2003, do we still need to check that the forms are ordered correctly in the OPTIONAL selections, or was that included in #503?

**Comment by OmarAI2003** [comment]
No @andrewtavis, we still need to check for that, but it will be easy since the functions `extract_form_qids` and `extract_form_rep_label` you defined can be utilized effectively for this, and I can work on it too.

**Comment by andrewtavis** [comment]
Awesome, @OmarAI2003 :) Looming forward and thanks for the continued efforts!

**Comment by OmarAI2003** [comment]
> @OmarAI2003, do we still need to check that the forms are ordered correctly in the OPTIONAL selections, or was that included in #503?

Just to make sure before I start working on the final part to close this issue. My understanding is that we need to ensure the order of the QIDs matches the order of the labels in the Optional statments. For example:

OPTIONAL {
    ?lexeme ontolex:lexicalForm ?masculineIndicativePastForm .
    ?masculineIndicativePastForm ontolex:representation ?masculineIndicativePast ;
      wikibase:grammaticalFeature wd:Q682111, wd:Q1994301, wd:Q499327 .
}

we need to check that the first QID (Q682111) corresponds to the first label, and so on. Is this what you meant in this comment?

**Comment by andrewtavis** [comment]
Exactly, @OmarAI2003 :) Thanks for checking! Really looking forward to finalizing this :)

**Comment by andrewtavis** [comment]
Thanks all for the efforts here! We're all closed up now, and the work here will make the growth of the query base so much more sustainable 😊 Appreciate the dedication and collaboration from all involved :)
