### ISSUE TITLE
Add translation files into the SQLite database process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#46]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In #23 we're working on getting JSON files for cross language translation such that we'd have source-target relationships between all Scribe languages. This issue would be the next step in the process that would add the new files into the SQLite database - specifically using [scribe_data/load/data_to_sqlite.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/data_to_sqlite.py). 

### Contribution

Happy to assist someone with this :)

**Comment by lillian-mo** [comment]
Hi! I would be happy to help with this issue :)

**Comment by andrewtavis** [comment]
Thanks @lillian-mo!

**Comment by andrewtavis** [comment]
Hey @Jk40git 👋 A bit confused by the question. The file you mentioned is to update the selection of words that we get from Wikidata that are then machine translated :)

**Comment by Jk40git** [comment]
> Hey [@Jk40git](https://github.com/Jk40git) 👋 A bit confused by the question. The file you mentioned is to update the selection of words that we get from Wikidata that are then machine translated :)

all right. I wanted to know the translation files that are supposed to be added into the SQLite database

**Comment by andrewtavis** [comment]
Those are the formatted translation files that are coming from the new processes in the `formatted_data` directories :) I think that @lillian-mo is going to pick this up on Saturday when she's back in the sync 🙌

**Comment by andrewtavis** [comment]
Reassigning as I'll also be working on #70, and once that's done I'll finalize this :)

**Comment by andrewtavis** [comment]
Closed by aef7e5a 🚀 The SQLite database generation process now works for the new translation file format :)
