### ISSUE TITLE
Update list command formatting to look like total command

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#466]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One thing that would make the functionality of Scribe-Data a bit better is if the list command formatting was similar to that of the total command. As of now they're different, and the total command is a bit more clean. The formatting would be:

- `scribe-data l -lang` like the first column of `scribe-data t -lang LANG -a`
- `scribe-data l -dt` like the second column of `scribe-data t -lang LANG -a`
- `scribe-data l -a` like the first two columns of `scribe-data t -lang LANG -a` together

### Contribution

Would be great to get some help with this! :)

CC @OmarAI2003

**Comment by OmarAI2003** [comment]
Hi there! 😃

**Comment by OmarAI2003** [comment]
> @OmarAI2003 shall both work on this issue?

Sure, so far we've agreed that we only need to change the `l` command tables from single-line sperators to double-line separators. Do you think this covers all the formatting needed for the `list` and `total` commands to match?

**Comment by andrewtavis** [comment]
Closed by #472 🚀 Thanks for this, @OmarAI2003!
