### ISSUE TITLE
language identifier for Ibibio

### ISSUE THREAD

**Issue by Otom-obhazi** [scribe-org/Scribe-Data#469]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Ibibio

### Description

While working with a file to format verbs from Wikidata, it was discovered that there is no identifier for the Ibibio language in the current metadata structure. This lack of an identifier prevents the inclusion of Ibibio language entries in the dataset.

**Comment by andrewtavis** [comment]
I added it in the review of the Ibibio PR, so this is all done 😊

**Comment by Otom-obhazi** [comment]
thank you :)
