### ISSUE TITLE
Update the documentation for building docs.

### ISSUE THREAD

**Issue by KesharwaniArpita** [scribe-org/Scribe-Data#475]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The current documentation for building the Scribe-Data project documentation is outdated and missing some crucial information. Specifically, it does not mention the requirement for installing Pandoc, which is necessary for the rendering of `.ipynb` files and documentation build process to work correctly.

### Contribution

Happy to work and collaborate on this!! 😄

**Comment by andrewtavis** [comment]
Closing this as the work for it was done in removing the iPython notebooks from the documentation, as this was adding unnecessarily difficult requirements to the project.
