### ISSUE TITLE
Total Command HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#477]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

We can successfully get the query retried. [query_data](https://github.com/scribe-org/Scribe-Data/blob/5ec2860ac2714afb1bc56bf303fd06e3b6edfe66/src/scribe_data/wikidata/query_data.py#L221)

![image](https://github.com/user-attachments/assets/d2efff51-8dbf-4d16-8113-f79d6711b6f5)

But in total `scribe-data total -a` we got the error. and it doesn't retried.
![image](https://github.com/user-attachments/assets/db869a7b-7bec-4f56-b915-684a1e173ecb)

**Comment by andrewtavis** [comment]
Great thought on this, @axif0! Do you want to check this as well? :)

**Comment by axif0** [comment]
Ya. would like to.

**Comment by andrewtavis** [comment]
Closed by #488 :) Thanks, @axif0! 😊
