### ISSUE TITLE
Get CLI --all functionality Enhancement 

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#478]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently [Get functionality ](https://github.com/scribe-org/Scribe-Data/blob/5ec2860ac2714afb1bc56bf303fd06e3b6edfe66/src/scribe_data/cli/get.py#L97) is not functional.

We can improve Get cli function by implementing - 
 
- [x] scribe-data get --all (gets all language and all data-types)
- [x] scribe-data get --all -dt nouns (gets all nouns for all language)
- [x] scribe-data get --all -lang english (gets all data-types for english)

### Contribution

Happy to work and collaborate if anyone participate on this!! 😄

**Comment by KesharwaniArpita** [comment]
@axif0 Can I collaborate?

**Comment by axif0** [comment]
@KesharwaniArpita Ya for sure.. 😅

**Comment by andrewtavis** [comment]
So basically the suggestion here @axif0 is that we split the all functionality a bit more? As of now we have `scribe-data get -a`, but that's just for all languages and data types, so we'd also split it for all from a language and all from a data type? I marked the first checkbox as done, btw 😊

**Comment by KesharwaniArpita** [comment]
Hi @axif0 I have made the required changes fo the implementation of 3rd. Would you like to review them?

**Comment by andrewtavis** [comment]
Closed in #493 :) Thank you both for the great collaboration here!
