### ISSUE TITLE
clean up language tests within convert functionality

### ISSUE THREAD

**Issue by john-thuo1** [scribe-org/Scribe-Data#496]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Currently, the language tests within `tests/cli/test_convert.py` have been partially implemented and commented out. To improve test coverage and accuracy, we need to uncomment and update these tests to align with the new language metadata.

**Comment by john-thuo1** [comment]
@andrewtavis I will be wrapping up the remaining tests on - `tests/cli/test_convert.py`  here.

**Comment by andrewtavis** [comment]
Thanks @john-thuo1 :)

**Comment by andrewtavis** [comment]
Closed by #498 🚀 Thanks a lot for the work to complete this, @john-thuo1!
