### ISSUE TITLE
CI: tests for utility functions

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#50]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we only have a simple test of the [utility functions](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/utils.py) in the CI process for Scribe-Data that's found in [Scribe-Data/tests/load/test_update_utils.py](https://github.com/scribe-org/Scribe-Data/blob/main/tests/load/test_update_utils.py). Firstly this file needs to be renamed to reflect the new structure of the repo with the utils file now being in the `scribe_data` root rather than in the `load` directory. Beyond this, it would be great to add a few more tests to make sure that the team will be notified if the functions in this file have been changed in a way that introduces breaking changes. This process would then be ran for PRs within the [Scribe-Data CI process](https://github.com/scribe-org/Scribe-Data/blob/main/.github/workflows/python_package_ci.yaml).

### Contribution

Happy to support someone with interest in working on this or get to it myself eventually 😊

**Comment by m-charlton** [comment]
I'm willing to have a crack at this.

**Comment by andrewtavis** [comment]
Hey @m-charlton! 👋 Thanks for offering to help out :) :) Please let me know if you have any questions. Happy to go through the functions in the utils and discuss what possible tests for them could be 😊

**Comment by m-charlton** [comment]
Thanks. Should be O.K with test coverage. I suspect you'll get some questions from me concerning directory structure & test infrastructure.

I think the best course of action is for me to submit a draft PR for review to make sure I'm on the right track.

**Comment by andrewtavis** [comment]
This sounds like a great plan, @m-charlton 😊 Looking forward to the initial review :)

**Comment by m-charlton** [comment]
Just writing the test cases for `add_num_commas` and found out that the thousand comma separator formatting is supported by f-strings in Python +3.9:

```pycon
Python 3.9.4 (v3.9.4:1f2e3088f3, Apr  4 2021, 12:32:44) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f"{-0.9e-12:,}"
'-9e-13'
>>> f"{-0.9e12:,}"
'-900,000,000,000.0'
``` 

I was unaware of this. This of course means that the function could be rewritten as

```python
def add_num_commas(num) -> str:
    return f"{num:,}"
```

_or_ remove `add_num_commas` and replace with the f-string. Did a quick find/grep in the `src` directory and found the following uses:

```shell
src/scribe_data/extract_transform/process_unicode.py:202:    total_keywords = add_num_commas(num=len(keyword_dict))
src/scribe_data/extract_transform/process_wiki.py:145:            f"Randomly sampling {add_num_commas(len(selected_idxs))} {language.capitalize()} Wikipedia articles..."
src/scribe_data/extract_transform/update_data.py:345:                data_added_string += f"{add_num_commas(data_added_dict[l][wt])} {wt},"
```

I enclose a zip file of the, possibly redundant :wink:, tests for `add_num_commas`, to make sure I'm heading in the right direction.
[test_update_utils.py.zip](https://github.com/scribe-org/Scribe-Data/files/12659778/test_update_utils.py.zip)

**Comment by andrewtavis** [comment]
Hey @m-charlton! This is really cool! 😊 I’d be happy to remove it and just use the f-strings :) Thanks for the research!

**Comment by andrewtavis** [comment]
You’d be welcome to send the changes along to remove `add_num_commas` with the changes for this issue if that’d be of interest, @m-charlton :)

**Comment by m-charlton** [comment]
I can do that.

**Comment by andrewtavis** [comment]
Thank so much for this, @m-charlton! As stated, so excited to be getting to all of this :) :)
