### ISSUE TITLE
Redundant list command in Readthedocs

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#515]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

In [readthedocs](https://scribe-data.readthedocs.io/en/latest/scribe_data/cli.html), in list, there are two commands `scribe-data list` and `scribe-data list -a` which is basically same. Showing both cli cmd output probably redundant I think.  

![image](https://github.com/user-attachments/assets/c718aa44-e250-4788-89f0-6f975a55c528)

**Comment by andrewtavis** [comment]
Thanks for the issue, @axif0! Do you want to do a PR for this? :)

**Comment by andrewtavis** [comment]
We can also leave it for a new contributor if you'd prefer.

**Comment by axif0** [comment]
Okke.. Just adding note that we can add small description in List CLI command for better understanding, and in the redundant command we can marge two commands into one.

**Comment by andrewtavis** [comment]
So would you say that maybe `scribe-data list -a` would include a note that it's running for all and without the `-a` it wouldn't? The two functionalities should be combined right now, but if they're not they should be :)

**Comment by axif0** [comment]
@andrewtavis both functionalities are working.. I mean after the `Example output:` in List we can add small description like 

> The scribe-data list command (also accessible via scribe-data list -a) displays both the available languages and data types.

**Comment by andrewtavis** [comment]
Closed by #518 🚀 Thanks for checking the docs and being on top of all this, @axif0!
