### ISSUE TITLE
Add download Wikidata dump command to CLI

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#517]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Scribe-Data will be expanding its functionality to work from Wikidata dumps. The first step in this is to add the ability for the CLI to download Wikidata Lexeme dumps. The following command should be added in this issue:

```bash
# Latest dump:
scribe-data download --wikidata-dump
scribe-data d -wd

# Specific dump:
scribe-data download --wikidata-dump YYYYMMDD
scribe-data d -wd YYYYMMDD

# Specific output directory:
scribe-data download --wikidata-dump --output-dir DIRECTORY_PATH
scribe-data d -wd -od DIRECTORY_PATH
```

The above will download the dumps from [dumps.wikimedia.org/wikidatawiki/entities/](https://dumps.wikimedia.org/wikidatawiki/entities/). In the fist set of queries the latest `.json.bz2` file will be downloaded, and in the second the URL for the given `YYYYMMDD` stamp will be checked and a `.json.bz2` dump will be downloaded to the PWD. The third would add in an output directory path as is done on the get command, but let's not change the file name. We'll just allow the user to put it in a directory 😊

The functionality should be added in a file `src/scribe_data/cli/download.py`, with the option being added into `src/scribe_data/cli/main.py` :)

### Contribution

Being worked on by @axif0 as a part of Outreachy! 📶🚀

**Comment by axif0** [comment]
This should be like- 

![image](https://github.com/user-attachments/assets/89f288ae-fedf-4861-8210-eac53664d3be)

**Comment by axif0** [comment]
Apologize, if those features are not planed.. :disappointed:

**Comment by andrewtavis** [comment]
No need to apologize, @axif0! You're a part of planning the features :) :)

This seems good to me! We'll just take the next most recent one? If there's no most recent one we'll take the last most recent one?

**Comment by axif0** [comment]
> This seems good to me! We'll just take the next most recent one? If there's no most recent one we'll take the last most recent one?

Yes..
