### ISSUE TITLE
Make a Wikidata lexemes dump required for `scribe-data g -a`

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#519]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

This issue is to require the presence of a Wikidata lexemes dump in order to run the `scribe-data get --all` command. There are a few steps here:

- Add `--wikidata-dump (-wd)` as an argument for `get`
- If the user passes a `-wd` argument with `scribe-data g -a`, then this file will be checked for and reported back to the user that it has been found using the functionality of #518
- The user user doesn't pass a `-wd` argument, then we'll check to see if there's a Wikidata dump in the PWD
- If there is no `-wd` argument and no dump in the PWD, then the user will be prompted to download a dump using the functionality in #517
- If the user doesn't choose to download the dump, then the functionality is canceled (the options for downloading are `Yes/Cancel`)

### Contribution

@axif0 will be working on this as a part of Outrachy! 📶🚂

**Comment by axif0** [comment]
Are we want like this?

![image](https://github.com/user-attachments/assets/5bf62657-ef7a-4906-84a5-896d6692c100)

**Comment by andrewtavis** [comment]
Looking good, @axif0! Can we rename the directory `scribe_data_wikidata_lexeme_dumps` so we don't have a dash in it? :)

**Comment by andrewtavis** [comment]
Closed by #528 🏎️ Thanks for the quick work on the first three issue and for working towards our responsible Wikidata usage, @axif0!
