### ISSUE TITLE
Outreachy Scribe-Data tests round 1

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#529]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

In my work for Outreachy'25 I've recently added the following functions:

In [download.py](https://github.com/scribe-org/Scribe-Data/blob/962684a8a873ff644888ee6de1c12320ed027b1a/src/scribe_data/cli/download.py) file consists of those functions:

- [x] [parse_date](https://github.com/scribe-org/Scribe-Data/pull/528/files#diff-521e9e4991b67c9764985290405a87490e0a7c76b0b83e03e9eb9f04e2dff444R37)
- [x] [available_closest_lexeme_dumpfile](https://github.com/scribe-org/Scribe-Data/pull/528/files#diff-521e9e4991b67c9764985290405a87490e0a7c76b0b83e03e9eb9f04e2dff444R70)
- [x] [download_wd_lexeme_dump](https://github.com/scribe-org/Scribe-Data/pull/528/files#diff-521e9e4991b67c9764985290405a87490e0a7c76b0b83e03e9eb9f04e2dff444R118)
  - [x] [check_wd_dump_exists](https://github.com/scribe-org/Scribe-Data/pull/528/files#diff-521e9e4991b67c9764985290405a87490e0a7c76b0b83e03e9eb9f04e2dff444R137)
- [x] [wd_lexeme_dump_download_wrapper](https://github.com/scribe-org/Scribe-Data/pull/528/files#diff-521e9e4991b67c9764985290405a87490e0a7c76b0b83e03e9eb9f04e2dff444R213)

  
This issue is to write and track all tests, each of the above functions for translations. 
Will update the description in future for upcoming works. 

### Contribution
Happy to work on this.

**Comment by andrewtavis** [comment]
Thanks so much for making this issue, @axif0! You're welcome to get to this whenever you can :)

**Comment by andrewtavis** [comment]
Closed by #530 🚀 Thanks for keeping track of the testing coverage and addressing it so quickly, @axif0! Great progress so far 😊
