### ISSUE TITLE
Version comparison fails due to inconsistent version string formats

### ISSUE THREAD

**Issue by axif0** [scribe-org/Scribe-Data#534]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The version comparison in [get_version_message()](https://github.com/scribe-org/Scribe-Data/blob/dd50d8dcbdbd624e84da9d5897f1ecd6c8adb88d/src/scribe_data/cli/version.py#L56) incorrectly reports available updates when local and latest versions are the same, due to mismatched string formats `("v" prefix and "Scribe-Data" prefix inconsistencies).`

![image](https://github.com/user-attachments/assets/6f59e741-2f28-4ccb-bde0-78681e818f36)

**Contribution**

Happy to review a PR when one's open and support with answers to any questions! 😊

**Comment by andrewtavis** [comment]
Thanks for opening this, @axif0! Great to see that you're testing so much of the package :) :)

**Comment by harikrishnatp** [comment]
I've identified where it's going wrong. In the [get_version_message()](https://github.com/scribe-org/Scribe-Data/blob/dd50d8dcbdbd624e84da9d5897f1ecd6c8adb88d/src/scribe_data/cli/version.py#L56) function, the value fetched from Github only has Scribe-Data without the `v` prefix while the value stored in local_version has Scribe-Data with a `v`. I could just standardise the version by removing `Scribe-Data` prefix from both for comparing and then adding v.

Also, the `pip scribe-data --upgrade` command is wrong, I fixed that as well

**Comment by axif0** [comment]
Nice thought.. Do you want to be assign on the issue and work on this? @harikrishnatp

**Comment by harikrishnatp** [comment]
@axif0 Yeah, sure

**Comment by axif0** [comment]
Great @harikrishnatp ~

**Comment by andrewtavis** [comment]
Closed by #535 🚀 Really appreciate the two great contributions to the project so far, @harikrishnatp 😊 Hope we can work with you more! Please let us know if you'd have interest in another issue here or in another Scribe project ✨

**Comment by harikrishnatp** [comment]
Thank you for the kind words and the feedback! I'll be more careful about keeping file changes to their respective PRs! 😄

**Comment by harikrishnatp** [comment]
Thank you so much for the encouragement and support! I'm really glad to contribute to Scribe Data and would definitely be interested in taking on another issue or exploring other projects. Could you please give me any suggestions on any other issues or in another scribe project ? 😄
