### ISSUE TITLE
Refactor ISO code usage using Python langcodes

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#55]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Something that I realized while doing a project for work is that there is a Python package [langcodes](https://github.com/rspeer/langcodes) that can handle a lot of the ISO-2 code work we're doing with Scribe-Data. Adding this to the dependencies would also make adding new languages to the data process easier in the future :)

### Contribution

Happy to support someone who has interest in working on this!

**Comment by andrewtavis** [comment]
Ping @m-charlton: definitely not the most difficult of issues, but this would be a solid one to pick up for now :) I'll get to the merges soon!

**Comment by andrewtavis** [comment]
This would basically allow us to remove this data from the JSON once that's merged :)

**Comment by shashank-iitbhu** [comment]
@andrewtavis I have setup the development environment locally. I can see two functions ```get_language_iso``` and ```get_language_from_iso``` in ```src/scribe_data/utlis.py``` . You can assign me this issue, so that I can go ahead and create a draft PR, [Link to the langcodes library](https://pypi.org/project/langcodes/).

**Comment by andrewtavis** [comment]
Thanks @shashank-iitbhu! Really appreciate all the details! Let me know if there's anything I can to do help!
