### ISSUE TITLE
Standardize function doc strings across Scribe-Data

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#56]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As of now we're using two different styles of doc strings for functions in Scribe-Data. This issue would be to standardize them such that we have a consistent style of documentation throughout the codebase.

### Contribution

Happy to support with this! I'm about to make another issue for creating [readthedocs](https://about.readthedocs.com/?ref=readthedocs.com) documentation. That issue should be worked on in combination with this one such that we can first check which style of doc string is preferable based on how it's rendered, and then we can make the changes to standardize them :) :)

**Comment by andrewtavis** [comment]
CC @m-charlton :) Making the issue for readthedocs now 🙃

**Comment by Jk40git** [comment]
@andrewtavis I would like to be assigned for this issue.

**Comment by andrewtavis** [comment]
Makes sense, @Jk40git! I'll try to get to the reviews soon :)

**Comment by Jk40git** [comment]
> Makes sense, @Jk40git! I'll try to get to the reviews soon :)

all right will be glad

**Comment by andrewtavis** [comment]
Closed via #63 and #64 :) Thanks @Jk40git! Appreciate the help 😊

**Comment by Jk40git** [comment]
> Closed via #63 and #64 :) Thanks @Jk40git! Appreciate the help 😊

You are welcome
