### ISSUE TITLE
Data process for Greek verbs

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Data#66]
### Terms

- [X] I have searched [open and closed data issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Adata+)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Languages

Greek

### Description

Breaking up the existing issue #58 into separate issues for the data processes for Greek nouns and verbs.

This will be the issue for the SPARQL query for Greek verbs.

The [`WIKIDATAGUIDE.md`](https://github.com/scribe-org/Organization/blob/main/WIKIDATAGUIDE.md) has some good info on Wikidata and SPARQL :blush: 

As reference, this is the query used for the Italian verbs [`.../Italian/verbs/query_verbs.sparql`](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/Italian/verbs/query_verbs.sparql)

**Comment by shashank-iitbhu** [comment]
Hey! @wkyoshida I will work on Data process for Greek Verbs. Please assign.

**Comment by andrewtavis** [comment]
Thanks for the offer to help with this, @shashank-iitbhu! Would be great to get some experience with Wikidata 🚀 Let us know if you need any support!

**Comment by andrewtavis** [comment]
Will close this for now with ea88cbf as the support for Greek verbs is currently very low. I did add parts to the query for present tense conjugations, but I'm not sure how properties are going to be applied to the lexemes once they are added (i.e. are the editors going to follow `present tense` + `singular` as is suggested or do `present tense singular`).

Let's make a new issue once there's more coverage 😊
