### ISSUE TITLE
Add reference to the architecture diagrams

### ISSUE THREAD

**Issue by wkyoshida** [scribe-org/Scribe-Data#67]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

This issue is to add a blurb in the `README.md` informing there are architecture diagrams (in the Organization's [`ARCHITECTURE.md`](https://github.com/scribe-org/Organization/blob/main/ARCHITECTURE.md)) available with some overviews of the Scribe projects.

NOTE:
- The goal with the blurb is primarily to provide some helpful initial guidance to newcomers.
- This same blurb can later be copied then into other project's `README.md`s and elsewhere.

**Comment by Jk40git** [comment]
Working on this

**Comment by Jk40git** [comment]
@andrewtavis  I have just created a pull request for this issue please check and give me a feedback

**Comment by wkyoshida** [comment]
Closing via https://github.com/scribe-org/Scribe-Data/pull/82

Thanks @Jk40git! :rocket:

**Comment by andrewtavis** [comment]
Thanks for the initial commit @Jk40git and for the edits, @wkyoshida! I'll send it along to the other repos :)
