### ISSUE TITLE
Fix of Portuguese Verb process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#68]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

Hey there @wkyoshida 👋 I'm realizing that the Portuguese verbs process is a little bit screwed up in that we're not getting conjugations for an entire conjugation. If you check out `verbs_queries.json` in the [Portuguese verbs directory](https://github.com/scribe-org/Scribe-Data/tree/main/src/scribe_data/extract_transform/languages/Portuguese/verbs), we're not getting anything for what's supposed to be a perfect tense 🤔 This seems to be a mix of me not understanding Portuguese and also some weird modeling on Wikidata. Could you give [ser](https://www.wikidata.org/wiki/Lexeme:L39470) and maybe a few other verbs a look and let me know what forms we should include. Generally we're trying to do present, any preterite/imperfect past forms, and for Portuguese it looks like future simple had good coverage, so that was included as well. For right now let's just do four total, so just the one that we're not getting anything from should be edited such that we get one more verb tense of value out of the process :)

### Contribution

Let's discuss this in the sync tomorrow! We'll need an issue for iOS as well once this is done to change what the verb form is in the app as well 😊

**Comment by shashank-iitbhu** [comment]
Hey @andrewtavis ! We're getting Perfect Tense conjugations but only for 36 verbs. Checked this by searching `perfFPS` in the `verbs_queried.json` file.
Here you can see that we are getting all six conjugations of perfect tense.
```
{
"fSimpTPP": "cantaram",
"fSimpSPP": "cantáreis",
"fSimpFPP": "cantáramos",
"fSimpTPS": "cantara",
"fSimpSPS": "cantaras",
"fSimpFPS": "cantara",
"impTPP": "cantavam",
"impSPP": "cantáveis",
"impFPP": "cantávamos",
"impTPS": "cantava",
"impSPS": "cantavas",
"impFPS": "cantava",
"presTPP": "cantam",
"presSPP": "cantais",
"presFPP": "cantamos",
"presTPS": "canta",
"presSPS": "cantas",
"presFPS": "canto",
"infinitive": "cantarmos",
"perfTPP": "cantaram",
"perfSPP": "cantastes",
"perfFPP": "cantamos",
"perfTPS": "cantou",
"perfSPS": "cantaste",
"perfFPS": "cantei"
},
```

**Comment by shashank-iitbhu** [comment]
Also noticed this towards the end of `verbs_queried.json` file:
For some verbs we are not getting any tense conjugations.
```
{
"infinitive": "ir"
},
{
"infinitive": "ter"
},
{
"infinitive": "segurar"
},
{
"infinitive": "vir"
},
{
"infinitive": "abolir"
},
{
"infinitive": "portar"
},
```

**Comment by andrewtavis** [comment]
I guess we're potentially good on this for now, but it would be good to check on Wikidata as well to see if maybe perfect tenses for Portuguese are normally being labeled in a different way than we're querying them 🤔

**Comment by andrewtavis** [comment]
Thanks for looking into this, @shashank-iitbhu!

**Comment by andrewtavis** [comment]
CC @wkyoshida

**Comment by andrewtavis** [comment]
54a5e36 seems to close this (for now). For now is because the past perfect PID that's being applied in Portuguese verbs isn't the standard one being applied in other languages, so it's likely that we'll need to change this at some point. I'll make an issue in Scribe-Server where we can discuss the process of checking the total coverage of prior files vs. the new ones such that we can do an alert if there's a major drop. There is a very likely chance that this PID will be changed. Quick fix if it is, but also best to get an explicit warning 😊
