### ISSUE TITLE
Extract noun gender functions to utils.py

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#69]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

As a part of refactoring the codebase, it would be great if the [map_genders function](https://github.com/scribe-org/Scribe-Data/blob/851410d678c61536735900c7b85df95dbafe5a58/src/scribe_data/extract_transform/languages/German/nouns/format_nouns.py#L36) that's used in various noun formatting processes was extracted to [utils.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/utils.py) and reused. This would be done for all currently finished noun formatting processes that have genders, so French, German, Italian, Portuguese, Russian, Spanish and Swedish.

### Contribution

Happy to discuss the work to be done and support implementation!

**Comment by ikeadeoyin** [comment]
Hello @andrewtavis,
I am interested in working on this.

**Comment by andrewtavis** [comment]
Assigned, and thanks for all the effort and collaboration so far!

**Comment by andrewtavis** [comment]
Closed via #84 🚀 Thanks so much for the contribution, @ikeadeoyin!
