### ISSUE TITLE
Generate all translations for the currently supported languages [was Colab testing]

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#70]
### Terms

- [X] I have searched [open and closed issues](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Issue

As a part of the process to work towards multi lingual translation, we need to test running the translation processes in a

**Comment by byt3h3ad** [comment]
hey! I would like to help with this issue.

**Comment by andrewtavis** [comment]
Hey @byt3h3ad 👋 Thanks so much for your offer to help! I'll assign you, and once we have one of the new ones finished we can get to this issue. You'd also be welcome to work on one of the translation issues as well! 😊

**Comment by andrewtavis** [comment]
Hey @byt3h3ad! We finally have some of the new translation processes up and running. If you wanted to give it a shot using the [scribe_data/extract_transform/languages/English/translations/translate_words.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/English/translations/translate_words.py) file and document how to get it up and running, then that'd be great!

**Comment by axif0** [comment]
hello, @andrewtavis I run the repo in [Google Colab](https://colab.research.google.com/drive/1mCzPnU0Qc_0QJcxu3IGeBgfOCpayo3wB?usp=sharing) As expected it shows same error which shows in the issue - #96

when i update the file [translation_utils](https://github.com/scribe-org/Scribe-Data/blob/b6b85c168bb77056ff586c952e434496b253e1a5/src/scribe_data/translation/translation_utils.py) it works in Google Colab.

**Comment by andrewtavis** [comment]
Nice, @axif0! Give me a moment and to do the check here, but this is great!

**Comment by andrewtavis** [comment]
Assigning you as well to show credit for the work here :)

**Comment by andrewtavis** [comment]
Switching the context of this issue to generating the translations from checking out Google Collab, as as @axif0 it sounds like the processes we have written here can't be finished even using Collab GPUs. I'm going to try to run these things locally over a few nights and then we can call this issue good, as the plan is not to have this process running on machine translations in the long term. Ultimately Scribe-Data will eventually run on Wiktionary based data, so let's close this with the current rendition and then start shifting towards the new methods :)

**Comment by andrewtavis** [comment]
@axif0, you were the one who'd said that the translation process didn't finish on Collab, right? Did you use GPUs for it, or just CPUs? To my memory they don't have GPUs available by default.

**Comment by axif0** [comment]
@andrewtavis i use `TPU v2.8`. Also the notebook is [here Google Colab](https://colab.research.google.com/drive/1mCzPnU0Qc_0QJcxu3IGeBgfOCpayo3wB?usp=sharing). 

![image](https://github.com/user-attachments/assets/7e2e6d28-01f5-4864-9d44-26a44ae6597e)

**Comment by andrewtavis** [comment]
Thanks, @axif0! Plan is that this weekend I'll get Colab pro and run through the process :) Will update after that!

**Comment by andrewtavis** [comment]
180ad64 is the result of all of the machine translations. We now need to rework the SQLite process to put them all in a `Translations.sqlite` file :)

**Comment by andrewtavis** [comment]
The above commits close this 🚀 The current data process takes an extremely long time that is basically preventative for it being ran again, but then we just need this for the next release, and then we'll move on to the new translation process once Outreachy is done 😊
