### ISSUE TITLE
[Deleted] Change translation data table values to averages per language

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#71]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One element of the translation process that will be split over many issues is that we want to be able to change the amount of translations that we report as being available for each language in [data_table.txt](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/_update_files/data_table.txt) into the average of all the languages sources that translate into it. A simple example, if we have 200 English to German pairs and 100 French to German pairs, then we would want the number of German translations to be listed as an average of 150. The reason that we're doing averages based on the target language is so that it's in line with the other numbers that we report: that we have this many nouns for the given keyboard language and this many verbs, etc.

- Note that this issue is still blocked, but only by #70

### Contribution

This issue will be blocked until the other translation issues have been finished. Happy to support or work on this myself when those are getting closer to completion!

**Comment by spalominor** [comment]
Can I work on this?

**Comment by andrewtavis** [comment]
Just assigned, @spalominor :) You'll need to wait a little bit on this for other people to be done with their translation issues, but hopefully you can get started by the end of the week 😊

**Comment by axif0** [comment]
Hello, @andrewtavis i can't find the file you mentioned [data_table.txt](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/_update_files/data_table.txt) . is it [this](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/load/update_files/total_data.json) ?

Also, can i work here? if you don't mind?

**Comment by andrewtavis** [comment]
Hey @axif0, the file was recently deleted :) Let's keep this one open as a reminder that we want to do this, but the work would be in Scribe-Server post the bi-weekly updates we have planned 😊

**Comment by andrewtavis** [comment]
Thanks for checking here!

**Comment by andrewtavis** [comment]
Deleting this as it's ultimately going to be remade as a Scribe-Server issue at some point :)
