### ISSUE TITLE
Create French to all other languages translation process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#73]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The goal of this issue is to create a process whereby a single file is used to translate all words within [French/translations/words_to_translate.json](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/French/translations/words_to_translate.json) to all other Scribe languages. To achieve this we'll be using [m2m100_418M](https://huggingface.co/facebook/m2m100_418M), with the output being a JSON file that has a string and keyed values for each language. This can then be transferred to an SQLite database table with each string in an index corresponding to a column value for each language.

Of specific importance is trying to get a metric of the accuracy of the translation and doing a cutoff such that we're no longer including low quality translations in Scribe applications :)

### Contribution

Happy to work on this or support someone with interest in working on it!

**Comment by Jk40git** [comment]
@andrewtavis can assign me here.

**Comment by andrewtavis** [comment]
Hey @Jk40git 👋 Before assigning, could you let me know if you've had some experience with some of the technologies beforehand? We're talking about doing a bit of machine translation here. We can work up to that, but if you've never done anything like it before, then maybe we'd need to switch over to a different issue for now to build your skills a bit. We can save this until one of the other translation issues is done - maybe by me - and then you can follow that one as an example.

**Comment by Jk40git** [comment]
Okay sounds great. I don't have any experience in machine translation though. okay I will have to switch to a different issue. 👍

**Comment by andrewtavis** [comment]
You can maybe work on this once another one like it is done and you can follow it as an example, @Jk40git :)

I'd suggest:
- https://github.com/scribe-org/Scribe-Data/issues/69
- https://github.com/scribe-org/Scribe-Data/issues/80
- https://github.com/scribe-org/Scribe-Data/issues/67

**Comment by Jk40git** [comment]
> You can maybe work on this once another one like it is done and you can follow it as an example, @Jk40git :)
> 
> I'd suggest:
> 
> * [Extract noun gender functions to utils.py #69](https://github.com/scribe-org/Scribe-Data/issues/69)
> * [Extract Wikidata loading and data exporting to utils.py #80](https://github.com/scribe-org/Scribe-Data/issues/80)
> * [Add reference to the architecture diagrams #67](https://github.com/scribe-org/Scribe-Data/issues/67)

Okay will go for the #67 first

**Comment by andrewtavis** [comment]
Feel free to write in there so we can assign :)

**Comment by andrewtavis** [comment]
Hey @Jk40git 👋 The process has been set up and we're ready to implement here :) It's actually quite streamlined now. If you make a version of [scribe_data/extract_transform/languages/English/translations/translate_words.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/English/translations/translate_words.py) that replaces `SRC_LANG` with French we should be good to go here 😊

**Comment by andrewtavis** [comment]
Thanks for this, @Jk40git! Closed via #108 with minor edits in 3140c02 :)
