### ISSUE TITLE
Create Portuguese to all other languages translation process

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#76]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

The goal of this issue is to create a process whereby a single file is used to translate all words within [Portuguese/translations/words_to_translate.json](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/Portuguese/translations/words_to_translate.json) to all other Scribe languages. To achieve this we'll be using [m2m100_418M](https://huggingface.co/facebook/m2m100_418M), with the output being a JSON file that has a string and keyed values for each language. This can then be transferred to an SQLite database table with each string in an index corresponding to a column value for each language.

Of specific importance is trying to get a metric of the accuracy of the translation and doing a cutoff such that we're no longer including low quality translations in Scribe applications :)

### Contribution

Happy to work on this or support someone with interest in working on it!

**Comment by Jag-Marcel** [comment]
I can take care of this one

**Comment by andrewtavis** [comment]
Hey @Jag-Marcel 👋 The process has been set up and we're ready to implement here :) It's actually quite streamlined now. If you make a version of [scribe_data/extract_transform/languages/English/translations/translate_words.py](https://github.com/scribe-org/Scribe-Data/blob/main/src/scribe_data/extract_transform/languages/English/translations/translate_words.py) that replaces `SRC_LANG` with Portuguese we should be good to go here 😊

Give it a test to see if it's working on your end by running the script in the header and letting it run for one batch so we can see what comes out!

**Comment by andrewtavis** [comment]
Closed via #112 🥳 Thanks @Jag-Marcel!
