### ISSUE TITLE
Update the upstream repo in the development environment guide

### ISSUE THREAD

**Issue by ikeadeoyin** [scribe-org/Scribe-Data#85]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

The issue is to update the upstream branch URL on the [development setup guide](https://scribe-data.readthedocs.io/en/latest/notes.html#dev-env)

<img width="793" alt="Screenshot 2024-02-28 at 00 17 55" src="https://github.com/scribe-org/Scribe-Data/assets/36523905/8419d959-d376-4d14-8aaf-91e4f7f4474e">

The guide sets the upstream URL as `git remote add upstream https://github.com/scribe-org/Scibe-Data.git`

The updated upstream URL should be `git remote add upstream https://github.com/scribe-org/Scribe-Data.git`

**Comment by wkyoshida** [comment]
Closing with #86 

Thanks @ikeadeoyin! :rocket:
