### ISSUE TITLE
Add Scribe-Data logo to the documentation sidebar header

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#90]
### Terms

- [X] I have searched [open and closed feature requests](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aissue+label%3Afeature)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Description

One change for the documentation that would be nice to have that is pretty standard is the logo of Scribe-Data in the top left of the documentation page in the header of the docs sidebar. This would replace the home icon and `Scribe-Data` as text as seen below:

![Screenshot_2024-03-05 07 51 40](https://github.com/scribe-org/Scribe-Data/assets/24387426/7ef9e5b8-b8bc-4e71-be2f-47a5674b0d8d)

One thing of note, the sidebar header color is blue, so we need a new color if we put the Scribe-Data logo there. We could for instance change the header color to `#F0F0EB` and the sidebar to `#F6F8FA` with the sidebar text being black instead of white :)

### Contribution

Happy to support with this! This issue is being made for someone who's interested in working on the docs 😊

**Comment by mhmohona** [comment]
I would like to work on this issue.

**Comment by andrewtavis** [comment]
Great @mhmohona! Let me know if there's anything we can do to help :)

**Comment by codeIntrovert** [comment]
is this issue fixed? Can I work on it?

**Comment by andrewtavis** [comment]
We already have a PR open for this in #92, @codeIntrovert. Thanks for your interest in helping though!

**Comment by andrewtavis** [comment]
One thing that got lost here that I'm realizing @mhmohona is that the version is now not appearing. Would you be able to send along a fix for that?
