### ISSUE TITLE
Add back in visibility of the version number to the docs sidebar

### ISSUE THREAD

**Issue by andrewtavis** [scribe-org/Scribe-Data#95]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

One issues from the most recent changes to the documentation layout to add in the logo in #90 was that the version number is now not visible. As seen in the image below, there's a space between the logo and search bar where the version is:

![Screenshot_2024-03-09 17 24 18](https://github.com/scribe-org/Scribe-Data/assets/24387426/77e5dd45-6b7b-4ece-bc65-b8c8ceacdfc6)

We could either change the text to black, or we can remove it entirely, but the former would be preferable :)

**Comment by andrewtavis** [comment]
CC @mhmohona, would you like to work on this?

**Comment by mhmohona** [comment]
Yes please!

**Comment by mhmohona** [comment]
@andrewtavis, so just to be clear, its the screenshot of the logo before my PR was merged. 
![image](https://github.com/scribe-org/Scribe-Data/assets/14244685/73625677-7c81-486c-86d7-0380685fce9d)

So I am seeing here the version was not been added previously. 

However, I am add about version info and and PR for this issue is on the way!

**Comment by andrewtavis** [comment]
Hmmmm, this is very interesting, @mhmohona 🤔 I think it's displayed differently based on the screen size or something, as I've always had the version number under the title on mine even before the logo was there :)

**Comment by mhmohona** [comment]
Sorry, my bad. It was my mistake 😬
sent fix in #100.

**Comment by andrewtavis** [comment]
Version number is visible now after c6d79f4 😊 We needed to make the text black for it to show up :)
