### ISSUE TITLE
Markdown to reStructuredText Format Issues

### ISSUE THREAD

**Issue by mhmohona** [scribe-org/Scribe-Data#98]
### Terms

- [X] I have searched all [open bug reports](https://github.com/scribe-org/Scribe-Data/issues?q=is%3Aopen+is%3Aissue+label%3Abug)
- [X] I agree to follow Scribe-Data's [Code of Conduct](https://github.com/scribe-org/Scribe-Data/blob/main/.github/CODE_OF_CONDUCT.md)

### Behavior

I've identified a formatting issue on the [Contributing to Scribe Data](https://scribe-data.readthedocs.io/en/latest/notes.html#id1) page, where Markdown syntax is not converting properly to reStructuredText in the documentation.

**Issue Description:**
In some cases, the links and note callouts formatted in Markdown are breaking upon conversion to `.rst`, leading to rendering issues on the Read the Docs site.

![Screenshot from 2024-03-10 08-49-46](https://github.com/scribe-org/Scribe-Data/assets/14244685/d52b8921-a405-4104-9243-8cd457f6b64c)

**Suggested Resolutions:**
- Adjust the `.rst` files post-conversion.
- Utilize `Pandoc` for improved conversion accuracy.
- Modify Markdown for better `.rst` compatibility.
- **Most efficient** - Transition to maintaining all documentation in .rst.

Implementing one of these solutions will help ensure that the documentation remains clear and navigable for all users.

**Comment by andrewtavis** [comment]
Thanks for the issue, @mhmohona! I think that converting the contributing file for the docs to .rst makes sense. Would you want to work on this?

**Comment by mhmohona** [comment]
Yes, I can work on it.

**Comment by andrewtavis** [comment]
Thanks @mhmohona! Let me know if there's anything I can do to help :)
